// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FKVerifyCodeGrpc.proto
// Protobuf C++ Version: 5.29.3

#ifndef FKVerifyCodeGrpc_2eproto_2epb_2eh
#define FKVerifyCodeGrpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FKVerifyCodeGrpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_FKVerifyCodeGrpc_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_FKVerifyCodeGrpc_2eproto;
namespace FKVerifyCodeGrpc {
class VerifyCodeRequestBody;
struct VerifyCodeRequestBodyDefaultTypeInternal;
extern VerifyCodeRequestBodyDefaultTypeInternal _VerifyCodeRequestBody_default_instance_;
class VerifyCodeResponseBody;
struct VerifyCodeResponseBodyDefaultTypeInternal;
extern VerifyCodeResponseBodyDefaultTypeInternal _VerifyCodeResponseBody_default_instance_;
}  // namespace FKVerifyCodeGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace FKVerifyCodeGrpc {

// ===================================================================


// -------------------------------------------------------------------

class VerifyCodeResponseBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKVerifyCodeGrpc.VerifyCodeResponseBody) */ {
 public:
  inline VerifyCodeResponseBody() : VerifyCodeResponseBody(nullptr) {}
  ~VerifyCodeResponseBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeResponseBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeResponseBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeResponseBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeResponseBody(const VerifyCodeResponseBody& from) : VerifyCodeResponseBody(nullptr, from) {}
  inline VerifyCodeResponseBody(VerifyCodeResponseBody&& from) noexcept
      : VerifyCodeResponseBody(nullptr, std::move(from)) {}
  inline VerifyCodeResponseBody& operator=(const VerifyCodeResponseBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeResponseBody& operator=(VerifyCodeResponseBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeResponseBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyCodeResponseBody* internal_default_instance() {
    return reinterpret_cast<const VerifyCodeResponseBody*>(
        &_VerifyCodeResponseBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(VerifyCodeResponseBody& a, VerifyCodeResponseBody& b) { a.Swap(&b); }
  inline void Swap(VerifyCodeResponseBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeResponseBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeResponseBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeResponseBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeResponseBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeResponseBody& from) { VerifyCodeResponseBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeResponseBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKVerifyCodeGrpc.VerifyCodeResponseBody"; }

 protected:
  explicit VerifyCodeResponseBody(::google::protobuf::Arena* arena);
  VerifyCodeResponseBody(::google::protobuf::Arena* arena, const VerifyCodeResponseBody& from);
  VerifyCodeResponseBody(::google::protobuf::Arena* arena, VerifyCodeResponseBody&& from) noexcept
      : VerifyCodeResponseBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kEmailFieldNumber = 4,
    kVerifyCodeFieldNumber = 5,
    kStatusCodeFieldNumber = 1,
    kRequestTypeFieldNumber = 3,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // string email = 4;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* value);

  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(
      const std::string& value);
  std::string* _internal_mutable_email();

  public:
  // string verify_code = 5;
  void clear_verify_code() ;
  const std::string& verify_code() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_verify_code(Arg_&& arg, Args_... args);
  std::string* mutable_verify_code();
  PROTOBUF_NODISCARD std::string* release_verify_code();
  void set_allocated_verify_code(std::string* value);

  private:
  const std::string& _internal_verify_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verify_code(
      const std::string& value);
  std::string* _internal_mutable_verify_code();

  public:
  // int32 status_code = 1;
  void clear_status_code() ;
  ::int32_t status_code() const;
  void set_status_code(::int32_t value);

  private:
  ::int32_t _internal_status_code() const;
  void _internal_set_status_code(::int32_t value);

  public:
  // int32 request_type = 3;
  void clear_request_type() ;
  ::int32_t request_type() const;
  void set_request_type(::int32_t value);

  private:
  ::int32_t _internal_request_type() const;
  void _internal_set_request_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKVerifyCodeGrpc.VerifyCodeResponseBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      71, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VerifyCodeResponseBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::google::protobuf::internal::ArenaStringPtr verify_code_;
    ::int32_t status_code_;
    ::int32_t request_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKVerifyCodeGrpc_2eproto;
};
// -------------------------------------------------------------------

class VerifyCodeRequestBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKVerifyCodeGrpc.VerifyCodeRequestBody) */ {
 public:
  inline VerifyCodeRequestBody() : VerifyCodeRequestBody(nullptr) {}
  ~VerifyCodeRequestBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeRequestBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeRequestBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeRequestBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeRequestBody(const VerifyCodeRequestBody& from) : VerifyCodeRequestBody(nullptr, from) {}
  inline VerifyCodeRequestBody(VerifyCodeRequestBody&& from) noexcept
      : VerifyCodeRequestBody(nullptr, std::move(from)) {}
  inline VerifyCodeRequestBody& operator=(const VerifyCodeRequestBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeRequestBody& operator=(VerifyCodeRequestBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeRequestBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyCodeRequestBody* internal_default_instance() {
    return reinterpret_cast<const VerifyCodeRequestBody*>(
        &_VerifyCodeRequestBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VerifyCodeRequestBody& a, VerifyCodeRequestBody& b) { a.Swap(&b); }
  inline void Swap(VerifyCodeRequestBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeRequestBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeRequestBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeRequestBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeRequestBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeRequestBody& from) { VerifyCodeRequestBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeRequestBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKVerifyCodeGrpc.VerifyCodeRequestBody"; }

 protected:
  explicit VerifyCodeRequestBody(::google::protobuf::Arena* arena);
  VerifyCodeRequestBody(::google::protobuf::Arena* arena, const VerifyCodeRequestBody& from);
  VerifyCodeRequestBody(::google::protobuf::Arena* arena, VerifyCodeRequestBody&& from) noexcept
      : VerifyCodeRequestBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmailFieldNumber = 2,
    kRequestTypeFieldNumber = 1,
  };
  // string email = 2;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* value);

  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(
      const std::string& value);
  std::string* _internal_mutable_email();

  public:
  // int32 request_type = 1;
  void clear_request_type() ;
  ::int32_t request_type() const;
  void set_request_type(::int32_t value);

  private:
  ::int32_t _internal_request_type() const;
  void _internal_set_request_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKVerifyCodeGrpc.VerifyCodeRequestBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VerifyCodeRequestBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::int32_t request_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKVerifyCodeGrpc_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VerifyCodeRequestBody

// int32 request_type = 1;
inline void VerifyCodeRequestBody::clear_request_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_type_ = 0;
}
inline ::int32_t VerifyCodeRequestBody::request_type() const {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeRequestBody.request_type)
  return _internal_request_type();
}
inline void VerifyCodeRequestBody::set_request_type(::int32_t value) {
  _internal_set_request_type(value);
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeRequestBody.request_type)
}
inline ::int32_t VerifyCodeRequestBody::_internal_request_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_type_;
}
inline void VerifyCodeRequestBody::_internal_set_request_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_type_ = value;
}

// string email = 2;
inline void VerifyCodeRequestBody::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
}
inline const std::string& VerifyCodeRequestBody::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeRequestBody.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeRequestBody::set_email(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeRequestBody.email)
}
inline std::string* VerifyCodeRequestBody::mutable_email() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:FKVerifyCodeGrpc.VerifyCodeRequestBody.email)
  return _s;
}
inline const std::string& VerifyCodeRequestBody::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void VerifyCodeRequestBody::_internal_set_email(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline std::string* VerifyCodeRequestBody::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable( GetArena());
}
inline std::string* VerifyCodeRequestBody::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKVerifyCodeGrpc.VerifyCodeRequestBody.email)
  return _impl_.email_.Release();
}
inline void VerifyCodeRequestBody::set_allocated_email(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKVerifyCodeGrpc.VerifyCodeRequestBody.email)
}

// -------------------------------------------------------------------

// VerifyCodeResponseBody

// int32 status_code = 1;
inline void VerifyCodeResponseBody::clear_status_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = 0;
}
inline ::int32_t VerifyCodeResponseBody::status_code() const {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeResponseBody.status_code)
  return _internal_status_code();
}
inline void VerifyCodeResponseBody::set_status_code(::int32_t value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeResponseBody.status_code)
}
inline ::int32_t VerifyCodeResponseBody::_internal_status_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_code_;
}
inline void VerifyCodeResponseBody::_internal_set_status_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = value;
}

// string message = 2;
inline void VerifyCodeResponseBody::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& VerifyCodeResponseBody::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeResponseBody.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeResponseBody::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeResponseBody.message)
}
inline std::string* VerifyCodeResponseBody::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:FKVerifyCodeGrpc.VerifyCodeResponseBody.message)
  return _s;
}
inline const std::string& VerifyCodeResponseBody::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void VerifyCodeResponseBody::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* VerifyCodeResponseBody::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* VerifyCodeResponseBody::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKVerifyCodeGrpc.VerifyCodeResponseBody.message)
  return _impl_.message_.Release();
}
inline void VerifyCodeResponseBody::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKVerifyCodeGrpc.VerifyCodeResponseBody.message)
}

// int32 request_type = 3;
inline void VerifyCodeResponseBody::clear_request_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_type_ = 0;
}
inline ::int32_t VerifyCodeResponseBody::request_type() const {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeResponseBody.request_type)
  return _internal_request_type();
}
inline void VerifyCodeResponseBody::set_request_type(::int32_t value) {
  _internal_set_request_type(value);
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeResponseBody.request_type)
}
inline ::int32_t VerifyCodeResponseBody::_internal_request_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_type_;
}
inline void VerifyCodeResponseBody::_internal_set_request_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_type_ = value;
}

// string email = 4;
inline void VerifyCodeResponseBody::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
}
inline const std::string& VerifyCodeResponseBody::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeResponseBody.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeResponseBody::set_email(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeResponseBody.email)
}
inline std::string* VerifyCodeResponseBody::mutable_email() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:FKVerifyCodeGrpc.VerifyCodeResponseBody.email)
  return _s;
}
inline const std::string& VerifyCodeResponseBody::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void VerifyCodeResponseBody::_internal_set_email(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline std::string* VerifyCodeResponseBody::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable( GetArena());
}
inline std::string* VerifyCodeResponseBody::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKVerifyCodeGrpc.VerifyCodeResponseBody.email)
  return _impl_.email_.Release();
}
inline void VerifyCodeResponseBody::set_allocated_email(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKVerifyCodeGrpc.VerifyCodeResponseBody.email)
}

// string verify_code = 5;
inline void VerifyCodeResponseBody::clear_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.ClearToEmpty();
}
inline const std::string& VerifyCodeResponseBody::verify_code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKVerifyCodeGrpc.VerifyCodeResponseBody.verify_code)
  return _internal_verify_code();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeResponseBody::set_verify_code(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKVerifyCodeGrpc.VerifyCodeResponseBody.verify_code)
}
inline std::string* VerifyCodeResponseBody::mutable_verify_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_verify_code();
  // @@protoc_insertion_point(field_mutable:FKVerifyCodeGrpc.VerifyCodeResponseBody.verify_code)
  return _s;
}
inline const std::string& VerifyCodeResponseBody::_internal_verify_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.verify_code_.Get();
}
inline void VerifyCodeResponseBody::_internal_set_verify_code(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.Set(value, GetArena());
}
inline std::string* VerifyCodeResponseBody::_internal_mutable_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.verify_code_.Mutable( GetArena());
}
inline std::string* VerifyCodeResponseBody::release_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKVerifyCodeGrpc.VerifyCodeResponseBody.verify_code)
  return _impl_.verify_code_.Release();
}
inline void VerifyCodeResponseBody::set_allocated_verify_code(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.verify_code_.IsDefault()) {
    _impl_.verify_code_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKVerifyCodeGrpc.VerifyCodeResponseBody.verify_code)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace FKVerifyCodeGrpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // FKVerifyCodeGrpc_2eproto_2epb_2eh
