// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FKGrpcService.proto
// Protobuf C++ Version: 5.29.3

#include "FKGrpcService.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace FKGrpcService {

inline constexpr VerifyCodeResponseBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        verify_code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_response_code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VerifyCodeResponseBody::VerifyCodeResponseBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VerifyCodeResponseBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VerifyCodeResponseBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VerifyCodeResponseBodyDefaultTypeInternal() {}
  union {
    VerifyCodeResponseBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyCodeResponseBodyDefaultTypeInternal _VerifyCodeResponseBody_default_instance_;

inline constexpr VerifyCodeRequestBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_request_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VerifyCodeRequestBody::VerifyCodeRequestBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VerifyCodeRequestBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VerifyCodeRequestBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VerifyCodeRequestBodyDefaultTypeInternal() {}
  union {
    VerifyCodeRequestBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyCodeRequestBodyDefaultTypeInternal _VerifyCodeRequestBody_default_instance_;

inline constexpr EncryptPasswordResponseBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        encrypted_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_response_code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EncryptPasswordResponseBody::EncryptPasswordResponseBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EncryptPasswordResponseBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncryptPasswordResponseBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptPasswordResponseBodyDefaultTypeInternal() {}
  union {
    EncryptPasswordResponseBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptPasswordResponseBodyDefaultTypeInternal _EncryptPasswordResponseBody_default_instance_;

inline constexpr EncryptPasswordRequestBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : hashed_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_request_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EncryptPasswordRequestBody::EncryptPasswordRequestBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EncryptPasswordRequestBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncryptPasswordRequestBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptPasswordRequestBodyDefaultTypeInternal() {}
  union {
    EncryptPasswordRequestBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptPasswordRequestBodyDefaultTypeInternal _EncryptPasswordRequestBody_default_instance_;

inline constexpr AuthenticatePwdResetResponseBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_response_code_{0},
        is_authenticated_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticatePwdResetResponseBody::AuthenticatePwdResetResponseBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AuthenticatePwdResetResponseBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticatePwdResetResponseBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticatePwdResetResponseBodyDefaultTypeInternal() {}
  union {
    AuthenticatePwdResetResponseBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticatePwdResetResponseBodyDefaultTypeInternal _AuthenticatePwdResetResponseBody_default_instance_;

inline constexpr AuthenticatePwdResetRequestBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : hashed_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        encrypted_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_request_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticatePwdResetRequestBody::AuthenticatePwdResetRequestBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AuthenticatePwdResetRequestBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticatePwdResetRequestBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticatePwdResetRequestBodyDefaultTypeInternal() {}
  union {
    AuthenticatePwdResetRequestBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticatePwdResetRequestBodyDefaultTypeInternal _AuthenticatePwdResetRequestBody_default_instance_;
}  // namespace FKGrpcService
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_FKGrpcService_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_FKGrpcService_2eproto = nullptr;
const ::uint32_t
    TableStruct_FKGrpcService_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeRequestBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeRequestBody, _impl_.rpc_request_type_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeRequestBody, _impl_.email_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeResponseBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeResponseBody, _impl_.rpc_response_code_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeResponseBody, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::VerifyCodeResponseBody, _impl_.verify_code_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordRequestBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordRequestBody, _impl_.rpc_request_type_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordRequestBody, _impl_.hashed_password_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordResponseBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordResponseBody, _impl_.rpc_response_code_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordResponseBody, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::EncryptPasswordResponseBody, _impl_.encrypted_password_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetRequestBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetRequestBody, _impl_.rpc_request_type_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetRequestBody, _impl_.hashed_password_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetRequestBody, _impl_.encrypted_password_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetResponseBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetResponseBody, _impl_.rpc_response_code_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetResponseBody, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::FKGrpcService::AuthenticatePwdResetResponseBody, _impl_.is_authenticated_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::FKGrpcService::VerifyCodeRequestBody)},
        {10, -1, -1, sizeof(::FKGrpcService::VerifyCodeResponseBody)},
        {21, -1, -1, sizeof(::FKGrpcService::EncryptPasswordRequestBody)},
        {31, -1, -1, sizeof(::FKGrpcService::EncryptPasswordResponseBody)},
        {42, -1, -1, sizeof(::FKGrpcService::AuthenticatePwdResetRequestBody)},
        {53, -1, -1, sizeof(::FKGrpcService::AuthenticatePwdResetResponseBody)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::FKGrpcService::_VerifyCodeRequestBody_default_instance_._instance,
    &::FKGrpcService::_VerifyCodeResponseBody_default_instance_._instance,
    &::FKGrpcService::_EncryptPasswordRequestBody_default_instance_._instance,
    &::FKGrpcService::_EncryptPasswordResponseBody_default_instance_._instance,
    &::FKGrpcService::_AuthenticatePwdResetRequestBody_default_instance_._instance,
    &::FKGrpcService::_AuthenticatePwdResetResponseBody_default_instance_._instance,
};
const char descriptor_table_protodef_FKGrpcService_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023FKGrpcService.proto\022\rFKGrpcService\"@\n\025"
    "VerifyCodeRequestBody\022\030\n\020rpc_request_typ"
    "e\030\001 \001(\005\022\r\n\005email\030\002 \001(\t\"Y\n\026VerifyCodeResp"
    "onseBody\022\031\n\021rpc_response_code\030\001 \001(\005\022\017\n\007m"
    "essage\030\002 \001(\t\022\023\n\013verify_code\030\003 \001(\t\"O\n\032Enc"
    "ryptPasswordRequestBody\022\030\n\020rpc_request_t"
    "ype\030\001 \001(\005\022\027\n\017hashed_password\030\002 \001(\t\"e\n\033En"
    "cryptPasswordResponseBody\022\031\n\021rpc_respons"
    "e_code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\032\n\022encrypt"
    "ed_password\030\003 \001(\t\"p\n\037AuthenticatePwdRese"
    "tRequestBody\022\030\n\020rpc_request_type\030\001 \001(\005\022\027"
    "\n\017hashed_password\030\002 \001(\t\022\032\n\022encrypted_pas"
    "sword\030\003 \001(\t\"h\n AuthenticatePwdResetRespo"
    "nseBody\022\031\n\021rpc_response_code\030\001 \001(\005\022\017\n\007me"
    "ssage\030\002 \001(\t\022\030\n\020is_authenticated\030\003 \001(\0102n\n"
    "\014Verification\022^\n\rGetVerifyCode\022$.FKGrpcS"
    "ervice.VerifyCodeRequestBody\032%.FKGrpcSer"
    "vice.VerifyCodeResponseBody\"\0002x\n\nEncrypt"
    "ion\022j\n\017EncryptPassword\022).FKGrpcService.E"
    "ncryptPasswordRequestBody\032*.FKGrpcServic"
    "e.EncryptPasswordResponseBody\"\0002\213\001\n\016Auth"
    "entication\022y\n\024AuthenticatePwdReset\022..FKG"
    "rpcService.AuthenticatePwdResetRequestBo"
    "dy\032/.FKGrpcService.AuthenticatePwdResetR"
    "esponseBody\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_FKGrpcService_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_FKGrpcService_2eproto = {
    false,
    false,
    981,
    descriptor_table_protodef_FKGrpcService_2eproto,
    "FKGrpcService.proto",
    &descriptor_table_FKGrpcService_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_FKGrpcService_2eproto::offsets,
    file_level_enum_descriptors_FKGrpcService_2eproto,
    file_level_service_descriptors_FKGrpcService_2eproto,
};
namespace FKGrpcService {
// ===================================================================

class VerifyCodeRequestBody::_Internal {
 public:
};

VerifyCodeRequestBody::VerifyCodeRequestBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.VerifyCodeRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE VerifyCodeRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::VerifyCodeRequestBody& from_msg)
      : email_(arena, from.email_),
        _cached_size_{0} {}

VerifyCodeRequestBody::VerifyCodeRequestBody(
    ::google::protobuf::Arena* arena,
    const VerifyCodeRequestBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyCodeRequestBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rpc_request_type_ = from._impl_.rpc_request_type_;

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.VerifyCodeRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE VerifyCodeRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : email_(arena),
        _cached_size_{0} {}

inline void VerifyCodeRequestBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_request_type_ = {};
}
VerifyCodeRequestBody::~VerifyCodeRequestBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.VerifyCodeRequestBody)
  SharedDtor(*this);
}
inline void VerifyCodeRequestBody::SharedDtor(MessageLite& self) {
  VerifyCodeRequestBody& this_ = static_cast<VerifyCodeRequestBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.email_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VerifyCodeRequestBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VerifyCodeRequestBody(arena);
}
constexpr auto VerifyCodeRequestBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCodeRequestBody),
                                            alignof(VerifyCodeRequestBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VerifyCodeRequestBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VerifyCodeRequestBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VerifyCodeRequestBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VerifyCodeRequestBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VerifyCodeRequestBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VerifyCodeRequestBody>(), &VerifyCodeRequestBody::ByteSizeLong,
            &VerifyCodeRequestBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VerifyCodeRequestBody, _impl_._cached_size_),
        false,
    },
    &VerifyCodeRequestBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VerifyCodeRequestBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> VerifyCodeRequestBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::VerifyCodeRequestBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string email = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeRequestBody, _impl_.email_)}},
    // int32 rpc_request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VerifyCodeRequestBody, _impl_.rpc_request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeRequestBody, _impl_.rpc_request_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_request_type = 1;
    {PROTOBUF_FIELD_OFFSET(VerifyCodeRequestBody, _impl_.rpc_request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string email = 2;
    {PROTOBUF_FIELD_OFFSET(VerifyCodeRequestBody, _impl_.email_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\0\5\0\0\0\0\0"
    "FKGrpcService.VerifyCodeRequestBody"
    "email"
  }},
};

PROTOBUF_NOINLINE void VerifyCodeRequestBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.VerifyCodeRequestBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.email_.ClearToEmpty();
  _impl_.rpc_request_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VerifyCodeRequestBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VerifyCodeRequestBody& this_ = static_cast<const VerifyCodeRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VerifyCodeRequestBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VerifyCodeRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.VerifyCodeRequestBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_request_type = 1;
          if (this_._internal_rpc_request_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_request_type(), target);
          }

          // string email = 2;
          if (!this_._internal_email().empty()) {
            const std::string& _s = this_._internal_email();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.VerifyCodeRequestBody.email");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.VerifyCodeRequestBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VerifyCodeRequestBody::ByteSizeLong(const MessageLite& base) {
          const VerifyCodeRequestBody& this_ = static_cast<const VerifyCodeRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VerifyCodeRequestBody::ByteSizeLong() const {
          const VerifyCodeRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.VerifyCodeRequestBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string email = 2;
            if (!this_._internal_email().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_email());
            }
            // int32 rpc_request_type = 1;
            if (this_._internal_rpc_request_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_request_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VerifyCodeRequestBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VerifyCodeRequestBody*>(&to_msg);
  auto& from = static_cast<const VerifyCodeRequestBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.VerifyCodeRequestBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (from._internal_rpc_request_type() != 0) {
    _this->_impl_.rpc_request_type_ = from._impl_.rpc_request_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyCodeRequestBody::CopyFrom(const VerifyCodeRequestBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.VerifyCodeRequestBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VerifyCodeRequestBody::InternalSwap(VerifyCodeRequestBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
        swap(_impl_.rpc_request_type_, other->_impl_.rpc_request_type_);
}

::google::protobuf::Metadata VerifyCodeRequestBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class VerifyCodeResponseBody::_Internal {
 public:
};

VerifyCodeResponseBody::VerifyCodeResponseBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.VerifyCodeResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE VerifyCodeResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::VerifyCodeResponseBody& from_msg)
      : message_(arena, from.message_),
        verify_code_(arena, from.verify_code_),
        _cached_size_{0} {}

VerifyCodeResponseBody::VerifyCodeResponseBody(
    ::google::protobuf::Arena* arena,
    const VerifyCodeResponseBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyCodeResponseBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rpc_response_code_ = from._impl_.rpc_response_code_;

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.VerifyCodeResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE VerifyCodeResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        verify_code_(arena),
        _cached_size_{0} {}

inline void VerifyCodeResponseBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_response_code_ = {};
}
VerifyCodeResponseBody::~VerifyCodeResponseBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.VerifyCodeResponseBody)
  SharedDtor(*this);
}
inline void VerifyCodeResponseBody::SharedDtor(MessageLite& self) {
  VerifyCodeResponseBody& this_ = static_cast<VerifyCodeResponseBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.verify_code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VerifyCodeResponseBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VerifyCodeResponseBody(arena);
}
constexpr auto VerifyCodeResponseBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCodeResponseBody),
                                            alignof(VerifyCodeResponseBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VerifyCodeResponseBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VerifyCodeResponseBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VerifyCodeResponseBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VerifyCodeResponseBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VerifyCodeResponseBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VerifyCodeResponseBody>(), &VerifyCodeResponseBody::ByteSizeLong,
            &VerifyCodeResponseBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_._cached_size_),
        false,
    },
    &VerifyCodeResponseBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VerifyCodeResponseBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 63, 2> VerifyCodeResponseBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::VerifyCodeResponseBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 rpc_response_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VerifyCodeResponseBody, _impl_.rpc_response_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.rpc_response_code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.message_)}},
    // string verify_code = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.verify_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_response_code = 1;
    {PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.rpc_response_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string verify_code = 3;
    {PROTOBUF_FIELD_OFFSET(VerifyCodeResponseBody, _impl_.verify_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\0\7\13\0\0\0\0"
    "FKGrpcService.VerifyCodeResponseBody"
    "message"
    "verify_code"
  }},
};

PROTOBUF_NOINLINE void VerifyCodeResponseBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.VerifyCodeResponseBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.verify_code_.ClearToEmpty();
  _impl_.rpc_response_code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VerifyCodeResponseBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VerifyCodeResponseBody& this_ = static_cast<const VerifyCodeResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VerifyCodeResponseBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VerifyCodeResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.VerifyCodeResponseBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_response_code = 1;
          if (this_._internal_rpc_response_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_response_code(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.VerifyCodeResponseBody.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string verify_code = 3;
          if (!this_._internal_verify_code().empty()) {
            const std::string& _s = this_._internal_verify_code();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.VerifyCodeResponseBody.verify_code");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.VerifyCodeResponseBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VerifyCodeResponseBody::ByteSizeLong(const MessageLite& base) {
          const VerifyCodeResponseBody& this_ = static_cast<const VerifyCodeResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VerifyCodeResponseBody::ByteSizeLong() const {
          const VerifyCodeResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.VerifyCodeResponseBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // string verify_code = 3;
            if (!this_._internal_verify_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_verify_code());
            }
            // int32 rpc_response_code = 1;
            if (this_._internal_rpc_response_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_response_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VerifyCodeResponseBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VerifyCodeResponseBody*>(&to_msg);
  auto& from = static_cast<const VerifyCodeResponseBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.VerifyCodeResponseBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_verify_code().empty()) {
    _this->_internal_set_verify_code(from._internal_verify_code());
  }
  if (from._internal_rpc_response_code() != 0) {
    _this->_impl_.rpc_response_code_ = from._impl_.rpc_response_code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyCodeResponseBody::CopyFrom(const VerifyCodeResponseBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.VerifyCodeResponseBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VerifyCodeResponseBody::InternalSwap(VerifyCodeResponseBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.verify_code_, &other->_impl_.verify_code_, arena);
        swap(_impl_.rpc_response_code_, other->_impl_.rpc_response_code_);
}

::google::protobuf::Metadata VerifyCodeResponseBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EncryptPasswordRequestBody::_Internal {
 public:
};

EncryptPasswordRequestBody::EncryptPasswordRequestBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.EncryptPasswordRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE EncryptPasswordRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::EncryptPasswordRequestBody& from_msg)
      : hashed_password_(arena, from.hashed_password_),
        _cached_size_{0} {}

EncryptPasswordRequestBody::EncryptPasswordRequestBody(
    ::google::protobuf::Arena* arena,
    const EncryptPasswordRequestBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EncryptPasswordRequestBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rpc_request_type_ = from._impl_.rpc_request_type_;

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.EncryptPasswordRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE EncryptPasswordRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : hashed_password_(arena),
        _cached_size_{0} {}

inline void EncryptPasswordRequestBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_request_type_ = {};
}
EncryptPasswordRequestBody::~EncryptPasswordRequestBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.EncryptPasswordRequestBody)
  SharedDtor(*this);
}
inline void EncryptPasswordRequestBody::SharedDtor(MessageLite& self) {
  EncryptPasswordRequestBody& this_ = static_cast<EncryptPasswordRequestBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.hashed_password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EncryptPasswordRequestBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EncryptPasswordRequestBody(arena);
}
constexpr auto EncryptPasswordRequestBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EncryptPasswordRequestBody),
                                            alignof(EncryptPasswordRequestBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EncryptPasswordRequestBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EncryptPasswordRequestBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EncryptPasswordRequestBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EncryptPasswordRequestBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EncryptPasswordRequestBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EncryptPasswordRequestBody>(), &EncryptPasswordRequestBody::ByteSizeLong,
            &EncryptPasswordRequestBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EncryptPasswordRequestBody, _impl_._cached_size_),
        false,
    },
    &EncryptPasswordRequestBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EncryptPasswordRequestBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 64, 2> EncryptPasswordRequestBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::EncryptPasswordRequestBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string hashed_password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EncryptPasswordRequestBody, _impl_.hashed_password_)}},
    // int32 rpc_request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EncryptPasswordRequestBody, _impl_.rpc_request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EncryptPasswordRequestBody, _impl_.rpc_request_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_request_type = 1;
    {PROTOBUF_FIELD_OFFSET(EncryptPasswordRequestBody, _impl_.rpc_request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string hashed_password = 2;
    {PROTOBUF_FIELD_OFFSET(EncryptPasswordRequestBody, _impl_.hashed_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\50\0\17\0\0\0\0\0"
    "FKGrpcService.EncryptPasswordRequestBody"
    "hashed_password"
  }},
};

PROTOBUF_NOINLINE void EncryptPasswordRequestBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.EncryptPasswordRequestBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.hashed_password_.ClearToEmpty();
  _impl_.rpc_request_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EncryptPasswordRequestBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EncryptPasswordRequestBody& this_ = static_cast<const EncryptPasswordRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EncryptPasswordRequestBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EncryptPasswordRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.EncryptPasswordRequestBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_request_type = 1;
          if (this_._internal_rpc_request_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_request_type(), target);
          }

          // string hashed_password = 2;
          if (!this_._internal_hashed_password().empty()) {
            const std::string& _s = this_._internal_hashed_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.EncryptPasswordRequestBody.hashed_password");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.EncryptPasswordRequestBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EncryptPasswordRequestBody::ByteSizeLong(const MessageLite& base) {
          const EncryptPasswordRequestBody& this_ = static_cast<const EncryptPasswordRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EncryptPasswordRequestBody::ByteSizeLong() const {
          const EncryptPasswordRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.EncryptPasswordRequestBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string hashed_password = 2;
            if (!this_._internal_hashed_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_hashed_password());
            }
            // int32 rpc_request_type = 1;
            if (this_._internal_rpc_request_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_request_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EncryptPasswordRequestBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EncryptPasswordRequestBody*>(&to_msg);
  auto& from = static_cast<const EncryptPasswordRequestBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.EncryptPasswordRequestBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_hashed_password().empty()) {
    _this->_internal_set_hashed_password(from._internal_hashed_password());
  }
  if (from._internal_rpc_request_type() != 0) {
    _this->_impl_.rpc_request_type_ = from._impl_.rpc_request_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EncryptPasswordRequestBody::CopyFrom(const EncryptPasswordRequestBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.EncryptPasswordRequestBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EncryptPasswordRequestBody::InternalSwap(EncryptPasswordRequestBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hashed_password_, &other->_impl_.hashed_password_, arena);
        swap(_impl_.rpc_request_type_, other->_impl_.rpc_request_type_);
}

::google::protobuf::Metadata EncryptPasswordRequestBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EncryptPasswordResponseBody::_Internal {
 public:
};

EncryptPasswordResponseBody::EncryptPasswordResponseBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.EncryptPasswordResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE EncryptPasswordResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::EncryptPasswordResponseBody& from_msg)
      : message_(arena, from.message_),
        encrypted_password_(arena, from.encrypted_password_),
        _cached_size_{0} {}

EncryptPasswordResponseBody::EncryptPasswordResponseBody(
    ::google::protobuf::Arena* arena,
    const EncryptPasswordResponseBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EncryptPasswordResponseBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rpc_response_code_ = from._impl_.rpc_response_code_;

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.EncryptPasswordResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE EncryptPasswordResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        encrypted_password_(arena),
        _cached_size_{0} {}

inline void EncryptPasswordResponseBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_response_code_ = {};
}
EncryptPasswordResponseBody::~EncryptPasswordResponseBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.EncryptPasswordResponseBody)
  SharedDtor(*this);
}
inline void EncryptPasswordResponseBody::SharedDtor(MessageLite& self) {
  EncryptPasswordResponseBody& this_ = static_cast<EncryptPasswordResponseBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.encrypted_password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EncryptPasswordResponseBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EncryptPasswordResponseBody(arena);
}
constexpr auto EncryptPasswordResponseBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EncryptPasswordResponseBody),
                                            alignof(EncryptPasswordResponseBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EncryptPasswordResponseBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EncryptPasswordResponseBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EncryptPasswordResponseBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EncryptPasswordResponseBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EncryptPasswordResponseBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EncryptPasswordResponseBody>(), &EncryptPasswordResponseBody::ByteSizeLong,
            &EncryptPasswordResponseBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_._cached_size_),
        false,
    },
    &EncryptPasswordResponseBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EncryptPasswordResponseBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 75, 2> EncryptPasswordResponseBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::EncryptPasswordResponseBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 rpc_response_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EncryptPasswordResponseBody, _impl_.rpc_response_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.rpc_response_code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.message_)}},
    // string encrypted_password = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.encrypted_password_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_response_code = 1;
    {PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.rpc_response_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string encrypted_password = 3;
    {PROTOBUF_FIELD_OFFSET(EncryptPasswordResponseBody, _impl_.encrypted_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\51\0\7\22\0\0\0\0"
    "FKGrpcService.EncryptPasswordResponseBody"
    "message"
    "encrypted_password"
  }},
};

PROTOBUF_NOINLINE void EncryptPasswordResponseBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.EncryptPasswordResponseBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.encrypted_password_.ClearToEmpty();
  _impl_.rpc_response_code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EncryptPasswordResponseBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EncryptPasswordResponseBody& this_ = static_cast<const EncryptPasswordResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EncryptPasswordResponseBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EncryptPasswordResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.EncryptPasswordResponseBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_response_code = 1;
          if (this_._internal_rpc_response_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_response_code(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.EncryptPasswordResponseBody.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string encrypted_password = 3;
          if (!this_._internal_encrypted_password().empty()) {
            const std::string& _s = this_._internal_encrypted_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.EncryptPasswordResponseBody.encrypted_password");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.EncryptPasswordResponseBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EncryptPasswordResponseBody::ByteSizeLong(const MessageLite& base) {
          const EncryptPasswordResponseBody& this_ = static_cast<const EncryptPasswordResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EncryptPasswordResponseBody::ByteSizeLong() const {
          const EncryptPasswordResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.EncryptPasswordResponseBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // string encrypted_password = 3;
            if (!this_._internal_encrypted_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_encrypted_password());
            }
            // int32 rpc_response_code = 1;
            if (this_._internal_rpc_response_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_response_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EncryptPasswordResponseBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EncryptPasswordResponseBody*>(&to_msg);
  auto& from = static_cast<const EncryptPasswordResponseBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.EncryptPasswordResponseBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_encrypted_password().empty()) {
    _this->_internal_set_encrypted_password(from._internal_encrypted_password());
  }
  if (from._internal_rpc_response_code() != 0) {
    _this->_impl_.rpc_response_code_ = from._impl_.rpc_response_code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EncryptPasswordResponseBody::CopyFrom(const EncryptPasswordResponseBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.EncryptPasswordResponseBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EncryptPasswordResponseBody::InternalSwap(EncryptPasswordResponseBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.encrypted_password_, &other->_impl_.encrypted_password_, arena);
        swap(_impl_.rpc_response_code_, other->_impl_.rpc_response_code_);
}

::google::protobuf::Metadata EncryptPasswordResponseBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthenticatePwdResetRequestBody::_Internal {
 public:
};

AuthenticatePwdResetRequestBody::AuthenticatePwdResetRequestBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.AuthenticatePwdResetRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticatePwdResetRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::AuthenticatePwdResetRequestBody& from_msg)
      : hashed_password_(arena, from.hashed_password_),
        encrypted_password_(arena, from.encrypted_password_),
        _cached_size_{0} {}

AuthenticatePwdResetRequestBody::AuthenticatePwdResetRequestBody(
    ::google::protobuf::Arena* arena,
    const AuthenticatePwdResetRequestBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthenticatePwdResetRequestBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.rpc_request_type_ = from._impl_.rpc_request_type_;

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.AuthenticatePwdResetRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticatePwdResetRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : hashed_password_(arena),
        encrypted_password_(arena),
        _cached_size_{0} {}

inline void AuthenticatePwdResetRequestBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_request_type_ = {};
}
AuthenticatePwdResetRequestBody::~AuthenticatePwdResetRequestBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.AuthenticatePwdResetRequestBody)
  SharedDtor(*this);
}
inline void AuthenticatePwdResetRequestBody::SharedDtor(MessageLite& self) {
  AuthenticatePwdResetRequestBody& this_ = static_cast<AuthenticatePwdResetRequestBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.hashed_password_.Destroy();
  this_._impl_.encrypted_password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AuthenticatePwdResetRequestBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AuthenticatePwdResetRequestBody(arena);
}
constexpr auto AuthenticatePwdResetRequestBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AuthenticatePwdResetRequestBody),
                                            alignof(AuthenticatePwdResetRequestBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AuthenticatePwdResetRequestBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AuthenticatePwdResetRequestBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AuthenticatePwdResetRequestBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AuthenticatePwdResetRequestBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AuthenticatePwdResetRequestBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AuthenticatePwdResetRequestBody>(), &AuthenticatePwdResetRequestBody::ByteSizeLong,
            &AuthenticatePwdResetRequestBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_._cached_size_),
        false,
    },
    &AuthenticatePwdResetRequestBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AuthenticatePwdResetRequestBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 87, 2> AuthenticatePwdResetRequestBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::AuthenticatePwdResetRequestBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 rpc_request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AuthenticatePwdResetRequestBody, _impl_.rpc_request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.rpc_request_type_)}},
    // string hashed_password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.hashed_password_)}},
    // string encrypted_password = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.encrypted_password_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_request_type = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.rpc_request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string hashed_password = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.hashed_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string encrypted_password = 3;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetRequestBody, _impl_.encrypted_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\55\0\17\22\0\0\0\0"
    "FKGrpcService.AuthenticatePwdResetRequestBody"
    "hashed_password"
    "encrypted_password"
  }},
};

PROTOBUF_NOINLINE void AuthenticatePwdResetRequestBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.AuthenticatePwdResetRequestBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.hashed_password_.ClearToEmpty();
  _impl_.encrypted_password_.ClearToEmpty();
  _impl_.rpc_request_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AuthenticatePwdResetRequestBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AuthenticatePwdResetRequestBody& this_ = static_cast<const AuthenticatePwdResetRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AuthenticatePwdResetRequestBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AuthenticatePwdResetRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.AuthenticatePwdResetRequestBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_request_type = 1;
          if (this_._internal_rpc_request_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_request_type(), target);
          }

          // string hashed_password = 2;
          if (!this_._internal_hashed_password().empty()) {
            const std::string& _s = this_._internal_hashed_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string encrypted_password = 3;
          if (!this_._internal_encrypted_password().empty()) {
            const std::string& _s = this_._internal_encrypted_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.AuthenticatePwdResetRequestBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AuthenticatePwdResetRequestBody::ByteSizeLong(const MessageLite& base) {
          const AuthenticatePwdResetRequestBody& this_ = static_cast<const AuthenticatePwdResetRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AuthenticatePwdResetRequestBody::ByteSizeLong() const {
          const AuthenticatePwdResetRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.AuthenticatePwdResetRequestBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string hashed_password = 2;
            if (!this_._internal_hashed_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_hashed_password());
            }
            // string encrypted_password = 3;
            if (!this_._internal_encrypted_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_encrypted_password());
            }
            // int32 rpc_request_type = 1;
            if (this_._internal_rpc_request_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_request_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AuthenticatePwdResetRequestBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthenticatePwdResetRequestBody*>(&to_msg);
  auto& from = static_cast<const AuthenticatePwdResetRequestBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.AuthenticatePwdResetRequestBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_hashed_password().empty()) {
    _this->_internal_set_hashed_password(from._internal_hashed_password());
  }
  if (!from._internal_encrypted_password().empty()) {
    _this->_internal_set_encrypted_password(from._internal_encrypted_password());
  }
  if (from._internal_rpc_request_type() != 0) {
    _this->_impl_.rpc_request_type_ = from._impl_.rpc_request_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticatePwdResetRequestBody::CopyFrom(const AuthenticatePwdResetRequestBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.AuthenticatePwdResetRequestBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthenticatePwdResetRequestBody::InternalSwap(AuthenticatePwdResetRequestBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hashed_password_, &other->_impl_.hashed_password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.encrypted_password_, &other->_impl_.encrypted_password_, arena);
        swap(_impl_.rpc_request_type_, other->_impl_.rpc_request_type_);
}

::google::protobuf::Metadata AuthenticatePwdResetRequestBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthenticatePwdResetResponseBody::_Internal {
 public:
};

AuthenticatePwdResetResponseBody::AuthenticatePwdResetResponseBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKGrpcService.AuthenticatePwdResetResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticatePwdResetResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKGrpcService::AuthenticatePwdResetResponseBody& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

AuthenticatePwdResetResponseBody::AuthenticatePwdResetResponseBody(
    ::google::protobuf::Arena* arena,
    const AuthenticatePwdResetResponseBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthenticatePwdResetResponseBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rpc_response_code_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, rpc_response_code_),
           offsetof(Impl_, is_authenticated_) -
               offsetof(Impl_, rpc_response_code_) +
               sizeof(Impl_::is_authenticated_));

  // @@protoc_insertion_point(copy_constructor:FKGrpcService.AuthenticatePwdResetResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticatePwdResetResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void AuthenticatePwdResetResponseBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rpc_response_code_),
           0,
           offsetof(Impl_, is_authenticated_) -
               offsetof(Impl_, rpc_response_code_) +
               sizeof(Impl_::is_authenticated_));
}
AuthenticatePwdResetResponseBody::~AuthenticatePwdResetResponseBody() {
  // @@protoc_insertion_point(destructor:FKGrpcService.AuthenticatePwdResetResponseBody)
  SharedDtor(*this);
}
inline void AuthenticatePwdResetResponseBody::SharedDtor(MessageLite& self) {
  AuthenticatePwdResetResponseBody& this_ = static_cast<AuthenticatePwdResetResponseBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AuthenticatePwdResetResponseBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AuthenticatePwdResetResponseBody(arena);
}
constexpr auto AuthenticatePwdResetResponseBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AuthenticatePwdResetResponseBody),
                                            alignof(AuthenticatePwdResetResponseBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AuthenticatePwdResetResponseBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AuthenticatePwdResetResponseBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AuthenticatePwdResetResponseBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AuthenticatePwdResetResponseBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AuthenticatePwdResetResponseBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AuthenticatePwdResetResponseBody>(), &AuthenticatePwdResetResponseBody::ByteSizeLong,
            &AuthenticatePwdResetResponseBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_._cached_size_),
        false,
    },
    &AuthenticatePwdResetResponseBody::kDescriptorMethods,
    &descriptor_table_FKGrpcService_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AuthenticatePwdResetResponseBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 62, 2> AuthenticatePwdResetResponseBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKGrpcService::AuthenticatePwdResetResponseBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 rpc_response_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AuthenticatePwdResetResponseBody, _impl_.rpc_response_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.rpc_response_code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.message_)}},
    // bool is_authenticated = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthenticatePwdResetResponseBody, _impl_.is_authenticated_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.is_authenticated_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc_response_code = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.rpc_response_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_authenticated = 3;
    {PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.is_authenticated_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\56\0\7\0\0\0\0\0"
    "FKGrpcService.AuthenticatePwdResetResponseBody"
    "message"
  }},
};

PROTOBUF_NOINLINE void AuthenticatePwdResetResponseBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKGrpcService.AuthenticatePwdResetResponseBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.rpc_response_code_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_authenticated_) -
      reinterpret_cast<char*>(&_impl_.rpc_response_code_)) + sizeof(_impl_.is_authenticated_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AuthenticatePwdResetResponseBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AuthenticatePwdResetResponseBody& this_ = static_cast<const AuthenticatePwdResetResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AuthenticatePwdResetResponseBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AuthenticatePwdResetResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKGrpcService.AuthenticatePwdResetResponseBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 rpc_response_code = 1;
          if (this_._internal_rpc_response_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_rpc_response_code(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKGrpcService.AuthenticatePwdResetResponseBody.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bool is_authenticated = 3;
          if (this_._internal_is_authenticated() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_is_authenticated(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKGrpcService.AuthenticatePwdResetResponseBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AuthenticatePwdResetResponseBody::ByteSizeLong(const MessageLite& base) {
          const AuthenticatePwdResetResponseBody& this_ = static_cast<const AuthenticatePwdResetResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AuthenticatePwdResetResponseBody::ByteSizeLong() const {
          const AuthenticatePwdResetResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKGrpcService.AuthenticatePwdResetResponseBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 rpc_response_code = 1;
            if (this_._internal_rpc_response_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_rpc_response_code());
            }
            // bool is_authenticated = 3;
            if (this_._internal_is_authenticated() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AuthenticatePwdResetResponseBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthenticatePwdResetResponseBody*>(&to_msg);
  auto& from = static_cast<const AuthenticatePwdResetResponseBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKGrpcService.AuthenticatePwdResetResponseBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_rpc_response_code() != 0) {
    _this->_impl_.rpc_response_code_ = from._impl_.rpc_response_code_;
  }
  if (from._internal_is_authenticated() != 0) {
    _this->_impl_.is_authenticated_ = from._impl_.is_authenticated_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticatePwdResetResponseBody::CopyFrom(const AuthenticatePwdResetResponseBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKGrpcService.AuthenticatePwdResetResponseBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthenticatePwdResetResponseBody::InternalSwap(AuthenticatePwdResetResponseBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.is_authenticated_)
      + sizeof(AuthenticatePwdResetResponseBody::_impl_.is_authenticated_)
      - PROTOBUF_FIELD_OFFSET(AuthenticatePwdResetResponseBody, _impl_.rpc_response_code_)>(
          reinterpret_cast<char*>(&_impl_.rpc_response_code_),
          reinterpret_cast<char*>(&other->_impl_.rpc_response_code_));
}

::google::protobuf::Metadata AuthenticatePwdResetResponseBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace FKGrpcService
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_FKGrpcService_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
