// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FKGrpcService.proto
#ifndef GRPC_FKGrpcService_2eproto__INCLUDED
#define GRPC_FKGrpcService_2eproto__INCLUDED

#include "FKGrpcService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace FKGrpcService {

class Verification final {
 public:
  static constexpr char const* service_full_name() {
    return "FKGrpcService.Verification";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::FKGrpcService::VerifyCodeResponseBody* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>> AsyncGetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>>(AsyncGetVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>> PrepareAsyncGetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>>(PrepareAsyncGetVerifyCodeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>* AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::VerifyCodeResponseBody>* PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::FKGrpcService::VerifyCodeResponseBody* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>> AsyncGetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>>(AsyncGetVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>> PrepareAsyncGetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>>(PrepareAsyncGetVerifyCodeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response, std::function<void(::grpc::Status)>) override;
      void GetVerifyCode(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>* AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::VerifyCodeResponseBody>* PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::FKGrpcService::VerifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetVerifyCode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetVerifyCode(::grpc::ServerContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVerifyCode(::grpc::ServerContext* context, ::FKGrpcService::VerifyCodeRequestBody* request, ::grpc::ServerAsyncResponseWriter< ::FKGrpcService::VerifyCodeResponseBody>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetVerifyCode<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::VerifyCodeRequestBody, ::FKGrpcService::VerifyCodeResponseBody>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FKGrpcService::VerifyCodeRequestBody* request, ::FKGrpcService::VerifyCodeResponseBody* response) { return this->GetVerifyCode(context, request, response); }));}
    void SetMessageAllocatorFor_GetVerifyCode(
        ::grpc::MessageAllocator< ::FKGrpcService::VerifyCodeRequestBody, ::FKGrpcService::VerifyCodeResponseBody>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::VerifyCodeRequestBody, ::FKGrpcService::VerifyCodeResponseBody>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetVerifyCode<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVerifyCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVerifyCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FKGrpcService::VerifyCodeRequestBody, ::FKGrpcService::VerifyCodeResponseBody>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FKGrpcService::VerifyCodeRequestBody, ::FKGrpcService::VerifyCodeResponseBody>* streamer) {
                       return this->StreamedGetVerifyCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::FKGrpcService::VerifyCodeRequestBody* /*request*/, ::FKGrpcService::VerifyCodeResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVerifyCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FKGrpcService::VerifyCodeRequestBody,::FKGrpcService::VerifyCodeResponseBody>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetVerifyCode<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetVerifyCode<Service > StreamedService;
};

class Encryption final {
 public:
  static constexpr char const* service_full_name() {
    return "FKGrpcService.Encryption";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::FKGrpcService::EncryptPasswordResponseBody* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>> AsyncEncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>>(AsyncEncryptPasswordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>> PrepareAsyncEncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>>(PrepareAsyncEncryptPasswordRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>* AsyncEncryptPasswordRaw(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::EncryptPasswordResponseBody>* PrepareAsyncEncryptPasswordRaw(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::FKGrpcService::EncryptPasswordResponseBody* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>> AsyncEncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>>(AsyncEncryptPasswordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>> PrepareAsyncEncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>>(PrepareAsyncEncryptPasswordRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response, std::function<void(::grpc::Status)>) override;
      void EncryptPassword(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>* AsyncEncryptPasswordRaw(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::EncryptPasswordResponseBody>* PrepareAsyncEncryptPasswordRaw(::grpc::ClientContext* context, const ::FKGrpcService::EncryptPasswordRequestBody& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EncryptPassword_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status EncryptPassword(::grpc::ServerContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncryptPassword(::grpc::ServerContext* context, ::FKGrpcService::EncryptPasswordRequestBody* request, ::grpc::ServerAsyncResponseWriter< ::FKGrpcService::EncryptPasswordResponseBody>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EncryptPassword<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::EncryptPasswordRequestBody, ::FKGrpcService::EncryptPasswordResponseBody>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FKGrpcService::EncryptPasswordRequestBody* request, ::FKGrpcService::EncryptPasswordResponseBody* response) { return this->EncryptPassword(context, request, response); }));}
    void SetMessageAllocatorFor_EncryptPassword(
        ::grpc::MessageAllocator< ::FKGrpcService::EncryptPasswordRequestBody, ::FKGrpcService::EncryptPasswordResponseBody>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::EncryptPasswordRequestBody, ::FKGrpcService::EncryptPasswordResponseBody>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncryptPassword(
      ::grpc::CallbackServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EncryptPassword<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncryptPassword(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EncryptPassword(context, request, response); }));
    }
    ~WithRawCallbackMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncryptPassword(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EncryptPassword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EncryptPassword() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FKGrpcService::EncryptPasswordRequestBody, ::FKGrpcService::EncryptPasswordResponseBody>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FKGrpcService::EncryptPasswordRequestBody, ::FKGrpcService::EncryptPasswordResponseBody>* streamer) {
                       return this->StreamedEncryptPassword(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EncryptPassword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EncryptPassword(::grpc::ServerContext* /*context*/, const ::FKGrpcService::EncryptPasswordRequestBody* /*request*/, ::FKGrpcService::EncryptPasswordResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEncryptPassword(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FKGrpcService::EncryptPasswordRequestBody,::FKGrpcService::EncryptPasswordResponseBody>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EncryptPassword<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EncryptPassword<Service > StreamedService;
};

class Authentication final {
 public:
  static constexpr char const* service_full_name() {
    return "FKGrpcService.Authentication";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>> AsyncAuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>>(AsyncAuthenticatePwdResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>> PrepareAsyncAuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>>(PrepareAsyncAuthenticatePwdResetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>* AsyncAuthenticatePwdResetRaw(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FKGrpcService::AuthenticatePwdResetResponseBody>* PrepareAsyncAuthenticatePwdResetRaw(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>> AsyncAuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>>(AsyncAuthenticatePwdResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>> PrepareAsyncAuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>>(PrepareAsyncAuthenticatePwdResetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response, std::function<void(::grpc::Status)>) override;
      void AuthenticatePwdReset(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>* AsyncAuthenticatePwdResetRaw(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FKGrpcService::AuthenticatePwdResetResponseBody>* PrepareAsyncAuthenticatePwdResetRaw(::grpc::ClientContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AuthenticatePwdReset_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthenticatePwdReset(::grpc::ServerContext* context, ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::grpc::ServerAsyncResponseWriter< ::FKGrpcService::AuthenticatePwdResetResponseBody>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AuthenticatePwdReset<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::AuthenticatePwdResetRequestBody, ::FKGrpcService::AuthenticatePwdResetResponseBody>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FKGrpcService::AuthenticatePwdResetRequestBody* request, ::FKGrpcService::AuthenticatePwdResetResponseBody* response) { return this->AuthenticatePwdReset(context, request, response); }));}
    void SetMessageAllocatorFor_AuthenticatePwdReset(
        ::grpc::MessageAllocator< ::FKGrpcService::AuthenticatePwdResetRequestBody, ::FKGrpcService::AuthenticatePwdResetResponseBody>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FKGrpcService::AuthenticatePwdResetRequestBody, ::FKGrpcService::AuthenticatePwdResetResponseBody>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthenticatePwdReset(
      ::grpc::CallbackServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AuthenticatePwdReset<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthenticatePwdReset(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AuthenticatePwdReset(context, request, response); }));
    }
    ~WithRawCallbackMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthenticatePwdReset(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthenticatePwdReset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AuthenticatePwdReset() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FKGrpcService::AuthenticatePwdResetRequestBody, ::FKGrpcService::AuthenticatePwdResetResponseBody>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FKGrpcService::AuthenticatePwdResetRequestBody, ::FKGrpcService::AuthenticatePwdResetResponseBody>* streamer) {
                       return this->StreamedAuthenticatePwdReset(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AuthenticatePwdReset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthenticatePwdReset(::grpc::ServerContext* /*context*/, const ::FKGrpcService::AuthenticatePwdResetRequestBody* /*request*/, ::FKGrpcService::AuthenticatePwdResetResponseBody* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthenticatePwdReset(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FKGrpcService::AuthenticatePwdResetRequestBody,::FKGrpcService::AuthenticatePwdResetResponseBody>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AuthenticatePwdReset<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AuthenticatePwdReset<Service > StreamedService;
};

}  // namespace FKGrpcService


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_FKGrpcService_2eproto__INCLUDED
