// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FKGrpcService.proto
// Protobuf C++ Version: 5.29.3

#ifndef FKGrpcService_2eproto_2epb_2eh
#define FKGrpcService_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FKGrpcService_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_FKGrpcService_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_FKGrpcService_2eproto;
namespace FKGrpcService {
class AuthenticatePwdResetRequestBody;
struct AuthenticatePwdResetRequestBodyDefaultTypeInternal;
extern AuthenticatePwdResetRequestBodyDefaultTypeInternal _AuthenticatePwdResetRequestBody_default_instance_;
class AuthenticatePwdResetResponseBody;
struct AuthenticatePwdResetResponseBodyDefaultTypeInternal;
extern AuthenticatePwdResetResponseBodyDefaultTypeInternal _AuthenticatePwdResetResponseBody_default_instance_;
class EncryptPasswordRequestBody;
struct EncryptPasswordRequestBodyDefaultTypeInternal;
extern EncryptPasswordRequestBodyDefaultTypeInternal _EncryptPasswordRequestBody_default_instance_;
class EncryptPasswordResponseBody;
struct EncryptPasswordResponseBodyDefaultTypeInternal;
extern EncryptPasswordResponseBodyDefaultTypeInternal _EncryptPasswordResponseBody_default_instance_;
class VerifyCodeRequestBody;
struct VerifyCodeRequestBodyDefaultTypeInternal;
extern VerifyCodeRequestBodyDefaultTypeInternal _VerifyCodeRequestBody_default_instance_;
class VerifyCodeResponseBody;
struct VerifyCodeResponseBodyDefaultTypeInternal;
extern VerifyCodeResponseBodyDefaultTypeInternal _VerifyCodeResponseBody_default_instance_;
}  // namespace FKGrpcService
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace FKGrpcService {

// ===================================================================


// -------------------------------------------------------------------

class VerifyCodeResponseBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.VerifyCodeResponseBody) */ {
 public:
  inline VerifyCodeResponseBody() : VerifyCodeResponseBody(nullptr) {}
  ~VerifyCodeResponseBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeResponseBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeResponseBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeResponseBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeResponseBody(const VerifyCodeResponseBody& from) : VerifyCodeResponseBody(nullptr, from) {}
  inline VerifyCodeResponseBody(VerifyCodeResponseBody&& from) noexcept
      : VerifyCodeResponseBody(nullptr, std::move(from)) {}
  inline VerifyCodeResponseBody& operator=(const VerifyCodeResponseBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeResponseBody& operator=(VerifyCodeResponseBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeResponseBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyCodeResponseBody* internal_default_instance() {
    return reinterpret_cast<const VerifyCodeResponseBody*>(
        &_VerifyCodeResponseBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(VerifyCodeResponseBody& a, VerifyCodeResponseBody& b) { a.Swap(&b); }
  inline void Swap(VerifyCodeResponseBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeResponseBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeResponseBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeResponseBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeResponseBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeResponseBody& from) { VerifyCodeResponseBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeResponseBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.VerifyCodeResponseBody"; }

 protected:
  explicit VerifyCodeResponseBody(::google::protobuf::Arena* arena);
  VerifyCodeResponseBody(::google::protobuf::Arena* arena, const VerifyCodeResponseBody& from);
  VerifyCodeResponseBody(::google::protobuf::Arena* arena, VerifyCodeResponseBody&& from) noexcept
      : VerifyCodeResponseBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kVerifyCodeFieldNumber = 3,
    kRpcResponseCodeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // string verify_code = 3;
  void clear_verify_code() ;
  const std::string& verify_code() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_verify_code(Arg_&& arg, Args_... args);
  std::string* mutable_verify_code();
  PROTOBUF_NODISCARD std::string* release_verify_code();
  void set_allocated_verify_code(std::string* value);

  private:
  const std::string& _internal_verify_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verify_code(
      const std::string& value);
  std::string* _internal_mutable_verify_code();

  public:
  // int32 rpc_response_code = 1;
  void clear_rpc_response_code() ;
  ::int32_t rpc_response_code() const;
  void set_rpc_response_code(::int32_t value);

  private:
  ::int32_t _internal_rpc_response_code() const;
  void _internal_set_rpc_response_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.VerifyCodeResponseBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      63, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VerifyCodeResponseBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr verify_code_;
    ::int32_t rpc_response_code_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};
// -------------------------------------------------------------------

class VerifyCodeRequestBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.VerifyCodeRequestBody) */ {
 public:
  inline VerifyCodeRequestBody() : VerifyCodeRequestBody(nullptr) {}
  ~VerifyCodeRequestBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VerifyCodeRequestBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VerifyCodeRequestBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VerifyCodeRequestBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline VerifyCodeRequestBody(const VerifyCodeRequestBody& from) : VerifyCodeRequestBody(nullptr, from) {}
  inline VerifyCodeRequestBody(VerifyCodeRequestBody&& from) noexcept
      : VerifyCodeRequestBody(nullptr, std::move(from)) {}
  inline VerifyCodeRequestBody& operator=(const VerifyCodeRequestBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyCodeRequestBody& operator=(VerifyCodeRequestBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyCodeRequestBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyCodeRequestBody* internal_default_instance() {
    return reinterpret_cast<const VerifyCodeRequestBody*>(
        &_VerifyCodeRequestBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VerifyCodeRequestBody& a, VerifyCodeRequestBody& b) { a.Swap(&b); }
  inline void Swap(VerifyCodeRequestBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyCodeRequestBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyCodeRequestBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VerifyCodeRequestBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VerifyCodeRequestBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VerifyCodeRequestBody& from) { VerifyCodeRequestBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VerifyCodeRequestBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.VerifyCodeRequestBody"; }

 protected:
  explicit VerifyCodeRequestBody(::google::protobuf::Arena* arena);
  VerifyCodeRequestBody(::google::protobuf::Arena* arena, const VerifyCodeRequestBody& from);
  VerifyCodeRequestBody(::google::protobuf::Arena* arena, VerifyCodeRequestBody&& from) noexcept
      : VerifyCodeRequestBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmailFieldNumber = 2,
    kRpcRequestTypeFieldNumber = 1,
  };
  // string email = 2;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* value);

  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(
      const std::string& value);
  std::string* _internal_mutable_email();

  public:
  // int32 rpc_request_type = 1;
  void clear_rpc_request_type() ;
  ::int32_t rpc_request_type() const;
  void set_rpc_request_type(::int32_t value);

  private:
  ::int32_t _internal_rpc_request_type() const;
  void _internal_set_rpc_request_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.VerifyCodeRequestBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      49, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VerifyCodeRequestBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::int32_t rpc_request_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};
// -------------------------------------------------------------------

class EncryptPasswordResponseBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.EncryptPasswordResponseBody) */ {
 public:
  inline EncryptPasswordResponseBody() : EncryptPasswordResponseBody(nullptr) {}
  ~EncryptPasswordResponseBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EncryptPasswordResponseBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EncryptPasswordResponseBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EncryptPasswordResponseBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline EncryptPasswordResponseBody(const EncryptPasswordResponseBody& from) : EncryptPasswordResponseBody(nullptr, from) {}
  inline EncryptPasswordResponseBody(EncryptPasswordResponseBody&& from) noexcept
      : EncryptPasswordResponseBody(nullptr, std::move(from)) {}
  inline EncryptPasswordResponseBody& operator=(const EncryptPasswordResponseBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline EncryptPasswordResponseBody& operator=(EncryptPasswordResponseBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EncryptPasswordResponseBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const EncryptPasswordResponseBody* internal_default_instance() {
    return reinterpret_cast<const EncryptPasswordResponseBody*>(
        &_EncryptPasswordResponseBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(EncryptPasswordResponseBody& a, EncryptPasswordResponseBody& b) { a.Swap(&b); }
  inline void Swap(EncryptPasswordResponseBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EncryptPasswordResponseBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EncryptPasswordResponseBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EncryptPasswordResponseBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EncryptPasswordResponseBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EncryptPasswordResponseBody& from) { EncryptPasswordResponseBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EncryptPasswordResponseBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.EncryptPasswordResponseBody"; }

 protected:
  explicit EncryptPasswordResponseBody(::google::protobuf::Arena* arena);
  EncryptPasswordResponseBody(::google::protobuf::Arena* arena, const EncryptPasswordResponseBody& from);
  EncryptPasswordResponseBody(::google::protobuf::Arena* arena, EncryptPasswordResponseBody&& from) noexcept
      : EncryptPasswordResponseBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kEncryptedPasswordFieldNumber = 3,
    kRpcResponseCodeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // string encrypted_password = 3;
  void clear_encrypted_password() ;
  const std::string& encrypted_password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_encrypted_password(Arg_&& arg, Args_... args);
  std::string* mutable_encrypted_password();
  PROTOBUF_NODISCARD std::string* release_encrypted_password();
  void set_allocated_encrypted_password(std::string* value);

  private:
  const std::string& _internal_encrypted_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_encrypted_password(
      const std::string& value);
  std::string* _internal_mutable_encrypted_password();

  public:
  // int32 rpc_response_code = 1;
  void clear_rpc_response_code() ;
  ::int32_t rpc_response_code() const;
  void set_rpc_response_code(::int32_t value);

  private:
  ::int32_t _internal_rpc_response_code() const;
  void _internal_set_rpc_response_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.EncryptPasswordResponseBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      75, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EncryptPasswordResponseBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr encrypted_password_;
    ::int32_t rpc_response_code_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};
// -------------------------------------------------------------------

class EncryptPasswordRequestBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.EncryptPasswordRequestBody) */ {
 public:
  inline EncryptPasswordRequestBody() : EncryptPasswordRequestBody(nullptr) {}
  ~EncryptPasswordRequestBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EncryptPasswordRequestBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EncryptPasswordRequestBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EncryptPasswordRequestBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline EncryptPasswordRequestBody(const EncryptPasswordRequestBody& from) : EncryptPasswordRequestBody(nullptr, from) {}
  inline EncryptPasswordRequestBody(EncryptPasswordRequestBody&& from) noexcept
      : EncryptPasswordRequestBody(nullptr, std::move(from)) {}
  inline EncryptPasswordRequestBody& operator=(const EncryptPasswordRequestBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline EncryptPasswordRequestBody& operator=(EncryptPasswordRequestBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EncryptPasswordRequestBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const EncryptPasswordRequestBody* internal_default_instance() {
    return reinterpret_cast<const EncryptPasswordRequestBody*>(
        &_EncryptPasswordRequestBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(EncryptPasswordRequestBody& a, EncryptPasswordRequestBody& b) { a.Swap(&b); }
  inline void Swap(EncryptPasswordRequestBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EncryptPasswordRequestBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EncryptPasswordRequestBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EncryptPasswordRequestBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EncryptPasswordRequestBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EncryptPasswordRequestBody& from) { EncryptPasswordRequestBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EncryptPasswordRequestBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.EncryptPasswordRequestBody"; }

 protected:
  explicit EncryptPasswordRequestBody(::google::protobuf::Arena* arena);
  EncryptPasswordRequestBody(::google::protobuf::Arena* arena, const EncryptPasswordRequestBody& from);
  EncryptPasswordRequestBody(::google::protobuf::Arena* arena, EncryptPasswordRequestBody&& from) noexcept
      : EncryptPasswordRequestBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHashedPasswordFieldNumber = 2,
    kRpcRequestTypeFieldNumber = 1,
  };
  // string hashed_password = 2;
  void clear_hashed_password() ;
  const std::string& hashed_password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_hashed_password(Arg_&& arg, Args_... args);
  std::string* mutable_hashed_password();
  PROTOBUF_NODISCARD std::string* release_hashed_password();
  void set_allocated_hashed_password(std::string* value);

  private:
  const std::string& _internal_hashed_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hashed_password(
      const std::string& value);
  std::string* _internal_mutable_hashed_password();

  public:
  // int32 rpc_request_type = 1;
  void clear_rpc_request_type() ;
  ::int32_t rpc_request_type() const;
  void set_rpc_request_type(::int32_t value);

  private:
  ::int32_t _internal_rpc_request_type() const;
  void _internal_set_rpc_request_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.EncryptPasswordRequestBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      64, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EncryptPasswordRequestBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr hashed_password_;
    ::int32_t rpc_request_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};
// -------------------------------------------------------------------

class AuthenticatePwdResetResponseBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.AuthenticatePwdResetResponseBody) */ {
 public:
  inline AuthenticatePwdResetResponseBody() : AuthenticatePwdResetResponseBody(nullptr) {}
  ~AuthenticatePwdResetResponseBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AuthenticatePwdResetResponseBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AuthenticatePwdResetResponseBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthenticatePwdResetResponseBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline AuthenticatePwdResetResponseBody(const AuthenticatePwdResetResponseBody& from) : AuthenticatePwdResetResponseBody(nullptr, from) {}
  inline AuthenticatePwdResetResponseBody(AuthenticatePwdResetResponseBody&& from) noexcept
      : AuthenticatePwdResetResponseBody(nullptr, std::move(from)) {}
  inline AuthenticatePwdResetResponseBody& operator=(const AuthenticatePwdResetResponseBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthenticatePwdResetResponseBody& operator=(AuthenticatePwdResetResponseBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthenticatePwdResetResponseBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthenticatePwdResetResponseBody* internal_default_instance() {
    return reinterpret_cast<const AuthenticatePwdResetResponseBody*>(
        &_AuthenticatePwdResetResponseBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(AuthenticatePwdResetResponseBody& a, AuthenticatePwdResetResponseBody& b) { a.Swap(&b); }
  inline void Swap(AuthenticatePwdResetResponseBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthenticatePwdResetResponseBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthenticatePwdResetResponseBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AuthenticatePwdResetResponseBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthenticatePwdResetResponseBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthenticatePwdResetResponseBody& from) { AuthenticatePwdResetResponseBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AuthenticatePwdResetResponseBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.AuthenticatePwdResetResponseBody"; }

 protected:
  explicit AuthenticatePwdResetResponseBody(::google::protobuf::Arena* arena);
  AuthenticatePwdResetResponseBody(::google::protobuf::Arena* arena, const AuthenticatePwdResetResponseBody& from);
  AuthenticatePwdResetResponseBody(::google::protobuf::Arena* arena, AuthenticatePwdResetResponseBody&& from) noexcept
      : AuthenticatePwdResetResponseBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kRpcResponseCodeFieldNumber = 1,
    kIsAuthenticatedFieldNumber = 3,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // int32 rpc_response_code = 1;
  void clear_rpc_response_code() ;
  ::int32_t rpc_response_code() const;
  void set_rpc_response_code(::int32_t value);

  private:
  ::int32_t _internal_rpc_response_code() const;
  void _internal_set_rpc_response_code(::int32_t value);

  public:
  // bool is_authenticated = 3;
  void clear_is_authenticated() ;
  bool is_authenticated() const;
  void set_is_authenticated(bool value);

  private:
  bool _internal_is_authenticated() const;
  void _internal_set_is_authenticated(bool value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.AuthenticatePwdResetResponseBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      62, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AuthenticatePwdResetResponseBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::int32_t rpc_response_code_;
    bool is_authenticated_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};
// -------------------------------------------------------------------

class AuthenticatePwdResetRequestBody final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FKGrpcService.AuthenticatePwdResetRequestBody) */ {
 public:
  inline AuthenticatePwdResetRequestBody() : AuthenticatePwdResetRequestBody(nullptr) {}
  ~AuthenticatePwdResetRequestBody() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AuthenticatePwdResetRequestBody* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AuthenticatePwdResetRequestBody));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthenticatePwdResetRequestBody(
      ::google::protobuf::internal::ConstantInitialized);

  inline AuthenticatePwdResetRequestBody(const AuthenticatePwdResetRequestBody& from) : AuthenticatePwdResetRequestBody(nullptr, from) {}
  inline AuthenticatePwdResetRequestBody(AuthenticatePwdResetRequestBody&& from) noexcept
      : AuthenticatePwdResetRequestBody(nullptr, std::move(from)) {}
  inline AuthenticatePwdResetRequestBody& operator=(const AuthenticatePwdResetRequestBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthenticatePwdResetRequestBody& operator=(AuthenticatePwdResetRequestBody&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthenticatePwdResetRequestBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthenticatePwdResetRequestBody* internal_default_instance() {
    return reinterpret_cast<const AuthenticatePwdResetRequestBody*>(
        &_AuthenticatePwdResetRequestBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AuthenticatePwdResetRequestBody& a, AuthenticatePwdResetRequestBody& b) { a.Swap(&b); }
  inline void Swap(AuthenticatePwdResetRequestBody* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthenticatePwdResetRequestBody* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthenticatePwdResetRequestBody* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AuthenticatePwdResetRequestBody>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthenticatePwdResetRequestBody& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthenticatePwdResetRequestBody& from) { AuthenticatePwdResetRequestBody::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AuthenticatePwdResetRequestBody* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FKGrpcService.AuthenticatePwdResetRequestBody"; }

 protected:
  explicit AuthenticatePwdResetRequestBody(::google::protobuf::Arena* arena);
  AuthenticatePwdResetRequestBody(::google::protobuf::Arena* arena, const AuthenticatePwdResetRequestBody& from);
  AuthenticatePwdResetRequestBody(::google::protobuf::Arena* arena, AuthenticatePwdResetRequestBody&& from) noexcept
      : AuthenticatePwdResetRequestBody(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHashedPasswordFieldNumber = 2,
    kEncryptedPasswordFieldNumber = 3,
    kRpcRequestTypeFieldNumber = 1,
  };
  // string hashed_password = 2;
  void clear_hashed_password() ;
  const std::string& hashed_password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_hashed_password(Arg_&& arg, Args_... args);
  std::string* mutable_hashed_password();
  PROTOBUF_NODISCARD std::string* release_hashed_password();
  void set_allocated_hashed_password(std::string* value);

  private:
  const std::string& _internal_hashed_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hashed_password(
      const std::string& value);
  std::string* _internal_mutable_hashed_password();

  public:
  // string encrypted_password = 3;
  void clear_encrypted_password() ;
  const std::string& encrypted_password() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_encrypted_password(Arg_&& arg, Args_... args);
  std::string* mutable_encrypted_password();
  PROTOBUF_NODISCARD std::string* release_encrypted_password();
  void set_allocated_encrypted_password(std::string* value);

  private:
  const std::string& _internal_encrypted_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_encrypted_password(
      const std::string& value);
  std::string* _internal_mutable_encrypted_password();

  public:
  // int32 rpc_request_type = 1;
  void clear_rpc_request_type() ;
  ::int32_t rpc_request_type() const;
  void set_rpc_request_type(::int32_t value);

  private:
  ::int32_t _internal_rpc_request_type() const;
  void _internal_set_rpc_request_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FKGrpcService.AuthenticatePwdResetRequestBody)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      87, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AuthenticatePwdResetRequestBody& from_msg);
    ::google::protobuf::internal::ArenaStringPtr hashed_password_;
    ::google::protobuf::internal::ArenaStringPtr encrypted_password_;
    ::int32_t rpc_request_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FKGrpcService_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VerifyCodeRequestBody

// int32 rpc_request_type = 1;
inline void VerifyCodeRequestBody::clear_rpc_request_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = 0;
}
inline ::int32_t VerifyCodeRequestBody::rpc_request_type() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.VerifyCodeRequestBody.rpc_request_type)
  return _internal_rpc_request_type();
}
inline void VerifyCodeRequestBody::set_rpc_request_type(::int32_t value) {
  _internal_set_rpc_request_type(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.VerifyCodeRequestBody.rpc_request_type)
}
inline ::int32_t VerifyCodeRequestBody::_internal_rpc_request_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_request_type_;
}
inline void VerifyCodeRequestBody::_internal_set_rpc_request_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = value;
}

// string email = 2;
inline void VerifyCodeRequestBody::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
}
inline const std::string& VerifyCodeRequestBody::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.VerifyCodeRequestBody.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeRequestBody::set_email(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.VerifyCodeRequestBody.email)
}
inline std::string* VerifyCodeRequestBody::mutable_email() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.VerifyCodeRequestBody.email)
  return _s;
}
inline const std::string& VerifyCodeRequestBody::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void VerifyCodeRequestBody::_internal_set_email(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline std::string* VerifyCodeRequestBody::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable( GetArena());
}
inline std::string* VerifyCodeRequestBody::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.VerifyCodeRequestBody.email)
  return _impl_.email_.Release();
}
inline void VerifyCodeRequestBody::set_allocated_email(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.VerifyCodeRequestBody.email)
}

// -------------------------------------------------------------------

// VerifyCodeResponseBody

// int32 rpc_response_code = 1;
inline void VerifyCodeResponseBody::clear_rpc_response_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = 0;
}
inline ::int32_t VerifyCodeResponseBody::rpc_response_code() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.VerifyCodeResponseBody.rpc_response_code)
  return _internal_rpc_response_code();
}
inline void VerifyCodeResponseBody::set_rpc_response_code(::int32_t value) {
  _internal_set_rpc_response_code(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.VerifyCodeResponseBody.rpc_response_code)
}
inline ::int32_t VerifyCodeResponseBody::_internal_rpc_response_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_response_code_;
}
inline void VerifyCodeResponseBody::_internal_set_rpc_response_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = value;
}

// string message = 2;
inline void VerifyCodeResponseBody::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& VerifyCodeResponseBody::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.VerifyCodeResponseBody.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeResponseBody::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.VerifyCodeResponseBody.message)
}
inline std::string* VerifyCodeResponseBody::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.VerifyCodeResponseBody.message)
  return _s;
}
inline const std::string& VerifyCodeResponseBody::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void VerifyCodeResponseBody::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* VerifyCodeResponseBody::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* VerifyCodeResponseBody::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.VerifyCodeResponseBody.message)
  return _impl_.message_.Release();
}
inline void VerifyCodeResponseBody::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.VerifyCodeResponseBody.message)
}

// string verify_code = 3;
inline void VerifyCodeResponseBody::clear_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.ClearToEmpty();
}
inline const std::string& VerifyCodeResponseBody::verify_code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.VerifyCodeResponseBody.verify_code)
  return _internal_verify_code();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VerifyCodeResponseBody::set_verify_code(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.VerifyCodeResponseBody.verify_code)
}
inline std::string* VerifyCodeResponseBody::mutable_verify_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_verify_code();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.VerifyCodeResponseBody.verify_code)
  return _s;
}
inline const std::string& VerifyCodeResponseBody::_internal_verify_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.verify_code_.Get();
}
inline void VerifyCodeResponseBody::_internal_set_verify_code(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.Set(value, GetArena());
}
inline std::string* VerifyCodeResponseBody::_internal_mutable_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.verify_code_.Mutable( GetArena());
}
inline std::string* VerifyCodeResponseBody::release_verify_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.VerifyCodeResponseBody.verify_code)
  return _impl_.verify_code_.Release();
}
inline void VerifyCodeResponseBody::set_allocated_verify_code(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.verify_code_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.verify_code_.IsDefault()) {
    _impl_.verify_code_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.VerifyCodeResponseBody.verify_code)
}

// -------------------------------------------------------------------

// EncryptPasswordRequestBody

// int32 rpc_request_type = 1;
inline void EncryptPasswordRequestBody::clear_rpc_request_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = 0;
}
inline ::int32_t EncryptPasswordRequestBody::rpc_request_type() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.EncryptPasswordRequestBody.rpc_request_type)
  return _internal_rpc_request_type();
}
inline void EncryptPasswordRequestBody::set_rpc_request_type(::int32_t value) {
  _internal_set_rpc_request_type(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.EncryptPasswordRequestBody.rpc_request_type)
}
inline ::int32_t EncryptPasswordRequestBody::_internal_rpc_request_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_request_type_;
}
inline void EncryptPasswordRequestBody::_internal_set_rpc_request_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = value;
}

// string hashed_password = 2;
inline void EncryptPasswordRequestBody::clear_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.ClearToEmpty();
}
inline const std::string& EncryptPasswordRequestBody::hashed_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.EncryptPasswordRequestBody.hashed_password)
  return _internal_hashed_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EncryptPasswordRequestBody::set_hashed_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.EncryptPasswordRequestBody.hashed_password)
}
inline std::string* EncryptPasswordRequestBody::mutable_hashed_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_hashed_password();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.EncryptPasswordRequestBody.hashed_password)
  return _s;
}
inline const std::string& EncryptPasswordRequestBody::_internal_hashed_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hashed_password_.Get();
}
inline void EncryptPasswordRequestBody::_internal_set_hashed_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.Set(value, GetArena());
}
inline std::string* EncryptPasswordRequestBody::_internal_mutable_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hashed_password_.Mutable( GetArena());
}
inline std::string* EncryptPasswordRequestBody::release_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.EncryptPasswordRequestBody.hashed_password)
  return _impl_.hashed_password_.Release();
}
inline void EncryptPasswordRequestBody::set_allocated_hashed_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hashed_password_.IsDefault()) {
    _impl_.hashed_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.EncryptPasswordRequestBody.hashed_password)
}

// -------------------------------------------------------------------

// EncryptPasswordResponseBody

// int32 rpc_response_code = 1;
inline void EncryptPasswordResponseBody::clear_rpc_response_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = 0;
}
inline ::int32_t EncryptPasswordResponseBody::rpc_response_code() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.EncryptPasswordResponseBody.rpc_response_code)
  return _internal_rpc_response_code();
}
inline void EncryptPasswordResponseBody::set_rpc_response_code(::int32_t value) {
  _internal_set_rpc_response_code(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.EncryptPasswordResponseBody.rpc_response_code)
}
inline ::int32_t EncryptPasswordResponseBody::_internal_rpc_response_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_response_code_;
}
inline void EncryptPasswordResponseBody::_internal_set_rpc_response_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = value;
}

// string message = 2;
inline void EncryptPasswordResponseBody::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& EncryptPasswordResponseBody::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.EncryptPasswordResponseBody.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EncryptPasswordResponseBody::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.EncryptPasswordResponseBody.message)
}
inline std::string* EncryptPasswordResponseBody::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.EncryptPasswordResponseBody.message)
  return _s;
}
inline const std::string& EncryptPasswordResponseBody::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void EncryptPasswordResponseBody::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* EncryptPasswordResponseBody::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* EncryptPasswordResponseBody::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.EncryptPasswordResponseBody.message)
  return _impl_.message_.Release();
}
inline void EncryptPasswordResponseBody::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.EncryptPasswordResponseBody.message)
}

// string encrypted_password = 3;
inline void EncryptPasswordResponseBody::clear_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.ClearToEmpty();
}
inline const std::string& EncryptPasswordResponseBody::encrypted_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.EncryptPasswordResponseBody.encrypted_password)
  return _internal_encrypted_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EncryptPasswordResponseBody::set_encrypted_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.EncryptPasswordResponseBody.encrypted_password)
}
inline std::string* EncryptPasswordResponseBody::mutable_encrypted_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_encrypted_password();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.EncryptPasswordResponseBody.encrypted_password)
  return _s;
}
inline const std::string& EncryptPasswordResponseBody::_internal_encrypted_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encrypted_password_.Get();
}
inline void EncryptPasswordResponseBody::_internal_set_encrypted_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.Set(value, GetArena());
}
inline std::string* EncryptPasswordResponseBody::_internal_mutable_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.encrypted_password_.Mutable( GetArena());
}
inline std::string* EncryptPasswordResponseBody::release_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.EncryptPasswordResponseBody.encrypted_password)
  return _impl_.encrypted_password_.Release();
}
inline void EncryptPasswordResponseBody::set_allocated_encrypted_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.encrypted_password_.IsDefault()) {
    _impl_.encrypted_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.EncryptPasswordResponseBody.encrypted_password)
}

// -------------------------------------------------------------------

// AuthenticatePwdResetRequestBody

// int32 rpc_request_type = 1;
inline void AuthenticatePwdResetRequestBody::clear_rpc_request_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = 0;
}
inline ::int32_t AuthenticatePwdResetRequestBody::rpc_request_type() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetRequestBody.rpc_request_type)
  return _internal_rpc_request_type();
}
inline void AuthenticatePwdResetRequestBody::set_rpc_request_type(::int32_t value) {
  _internal_set_rpc_request_type(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetRequestBody.rpc_request_type)
}
inline ::int32_t AuthenticatePwdResetRequestBody::_internal_rpc_request_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_request_type_;
}
inline void AuthenticatePwdResetRequestBody::_internal_set_rpc_request_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_request_type_ = value;
}

// string hashed_password = 2;
inline void AuthenticatePwdResetRequestBody::clear_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.ClearToEmpty();
}
inline const std::string& AuthenticatePwdResetRequestBody::hashed_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password)
  return _internal_hashed_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticatePwdResetRequestBody::set_hashed_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password)
}
inline std::string* AuthenticatePwdResetRequestBody::mutable_hashed_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_hashed_password();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password)
  return _s;
}
inline const std::string& AuthenticatePwdResetRequestBody::_internal_hashed_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hashed_password_.Get();
}
inline void AuthenticatePwdResetRequestBody::_internal_set_hashed_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.Set(value, GetArena());
}
inline std::string* AuthenticatePwdResetRequestBody::_internal_mutable_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hashed_password_.Mutable( GetArena());
}
inline std::string* AuthenticatePwdResetRequestBody::release_hashed_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password)
  return _impl_.hashed_password_.Release();
}
inline void AuthenticatePwdResetRequestBody::set_allocated_hashed_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hashed_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hashed_password_.IsDefault()) {
    _impl_.hashed_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.AuthenticatePwdResetRequestBody.hashed_password)
}

// string encrypted_password = 3;
inline void AuthenticatePwdResetRequestBody::clear_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.ClearToEmpty();
}
inline const std::string& AuthenticatePwdResetRequestBody::encrypted_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password)
  return _internal_encrypted_password();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticatePwdResetRequestBody::set_encrypted_password(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password)
}
inline std::string* AuthenticatePwdResetRequestBody::mutable_encrypted_password() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_encrypted_password();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password)
  return _s;
}
inline const std::string& AuthenticatePwdResetRequestBody::_internal_encrypted_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encrypted_password_.Get();
}
inline void AuthenticatePwdResetRequestBody::_internal_set_encrypted_password(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.Set(value, GetArena());
}
inline std::string* AuthenticatePwdResetRequestBody::_internal_mutable_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.encrypted_password_.Mutable( GetArena());
}
inline std::string* AuthenticatePwdResetRequestBody::release_encrypted_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password)
  return _impl_.encrypted_password_.Release();
}
inline void AuthenticatePwdResetRequestBody::set_allocated_encrypted_password(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encrypted_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.encrypted_password_.IsDefault()) {
    _impl_.encrypted_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.AuthenticatePwdResetRequestBody.encrypted_password)
}

// -------------------------------------------------------------------

// AuthenticatePwdResetResponseBody

// int32 rpc_response_code = 1;
inline void AuthenticatePwdResetResponseBody::clear_rpc_response_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = 0;
}
inline ::int32_t AuthenticatePwdResetResponseBody::rpc_response_code() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetResponseBody.rpc_response_code)
  return _internal_rpc_response_code();
}
inline void AuthenticatePwdResetResponseBody::set_rpc_response_code(::int32_t value) {
  _internal_set_rpc_response_code(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetResponseBody.rpc_response_code)
}
inline ::int32_t AuthenticatePwdResetResponseBody::_internal_rpc_response_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rpc_response_code_;
}
inline void AuthenticatePwdResetResponseBody::_internal_set_rpc_response_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rpc_response_code_ = value;
}

// string message = 2;
inline void AuthenticatePwdResetResponseBody::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& AuthenticatePwdResetResponseBody::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetResponseBody.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticatePwdResetResponseBody::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetResponseBody.message)
}
inline std::string* AuthenticatePwdResetResponseBody::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:FKGrpcService.AuthenticatePwdResetResponseBody.message)
  return _s;
}
inline const std::string& AuthenticatePwdResetResponseBody::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void AuthenticatePwdResetResponseBody::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* AuthenticatePwdResetResponseBody::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* AuthenticatePwdResetResponseBody::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FKGrpcService.AuthenticatePwdResetResponseBody.message)
  return _impl_.message_.Release();
}
inline void AuthenticatePwdResetResponseBody::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FKGrpcService.AuthenticatePwdResetResponseBody.message)
}

// bool is_authenticated = 3;
inline void AuthenticatePwdResetResponseBody::clear_is_authenticated() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_authenticated_ = false;
}
inline bool AuthenticatePwdResetResponseBody::is_authenticated() const {
  // @@protoc_insertion_point(field_get:FKGrpcService.AuthenticatePwdResetResponseBody.is_authenticated)
  return _internal_is_authenticated();
}
inline void AuthenticatePwdResetResponseBody::set_is_authenticated(bool value) {
  _internal_set_is_authenticated(value);
  // @@protoc_insertion_point(field_set:FKGrpcService.AuthenticatePwdResetResponseBody.is_authenticated)
}
inline bool AuthenticatePwdResetResponseBody::_internal_is_authenticated() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_authenticated_;
}
inline void AuthenticatePwdResetResponseBody::_internal_set_is_authenticated(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_authenticated_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace FKGrpcService


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // FKGrpcService_2eproto_2epb_2eh
