// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FKVerifyGrpc.proto

#include "FKVerifyGrpc.pb.h"
#include "FKVerifyGrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace FKVerifyGrpc {

static const char* VarifyCodeService_method_names[] = {
  "/FKVerifyGrpc.VarifyCodeService/GetVarifyCode",
};

std::unique_ptr< VarifyCodeService::Stub> VarifyCodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VarifyCodeService::Stub> stub(new VarifyCodeService::Stub(channel, options));
  return stub;
}

VarifyCodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVarifyCode_(VarifyCodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VarifyCodeService::Stub::GetVarifyCode(::grpc::ClientContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody& request, ::FKVerifyGrpc::VarifyCodeResponseBody* response) {
  return ::grpc::internal::BlockingUnaryCall< ::FKVerifyGrpc::VarifyCodeRequestBody, ::FKVerifyGrpc::VarifyCodeResponseBody, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVarifyCode_, context, request, response);
}

void VarifyCodeService::Stub::async::GetVarifyCode(::grpc::ClientContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody* request, ::FKVerifyGrpc::VarifyCodeResponseBody* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::FKVerifyGrpc::VarifyCodeRequestBody, ::FKVerifyGrpc::VarifyCodeResponseBody, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVarifyCode_, context, request, response, std::move(f));
}

void VarifyCodeService::Stub::async::GetVarifyCode(::grpc::ClientContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody* request, ::FKVerifyGrpc::VarifyCodeResponseBody* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVarifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::FKVerifyGrpc::VarifyCodeResponseBody>* VarifyCodeService::Stub::PrepareAsyncGetVarifyCodeRaw(::grpc::ClientContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::FKVerifyGrpc::VarifyCodeResponseBody, ::FKVerifyGrpc::VarifyCodeRequestBody, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVarifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::FKVerifyGrpc::VarifyCodeResponseBody>* VarifyCodeService::Stub::AsyncGetVarifyCodeRaw(::grpc::ClientContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVarifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VarifyCodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VarifyCodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VarifyCodeService::Service, ::FKVerifyGrpc::VarifyCodeRequestBody, ::FKVerifyGrpc::VarifyCodeResponseBody, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VarifyCodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FKVerifyGrpc::VarifyCodeRequestBody* req,
             ::FKVerifyGrpc::VarifyCodeResponseBody* resp) {
               return service->GetVarifyCode(ctx, req, resp);
             }, this)));
}

VarifyCodeService::Service::~Service() {
}

::grpc::Status VarifyCodeService::Service::GetVarifyCode(::grpc::ServerContext* context, const ::FKVerifyGrpc::VarifyCodeRequestBody* request, ::FKVerifyGrpc::VarifyCodeResponseBody* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace FKVerifyGrpc

