// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FKVerifyGrpc.proto
// Protobuf C++ Version: 5.29.3

#include "FKVerifyGrpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace FKVerifyGrpc {

inline constexpr VarifyCodeResponseBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        varify_code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_code_{0},
        request_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VarifyCodeResponseBody::VarifyCodeResponseBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VarifyCodeResponseBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VarifyCodeResponseBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VarifyCodeResponseBodyDefaultTypeInternal() {}
  union {
    VarifyCodeResponseBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VarifyCodeResponseBodyDefaultTypeInternal _VarifyCodeResponseBody_default_instance_;

inline constexpr VarifyCodeRequestBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        request_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VarifyCodeRequestBody::VarifyCodeRequestBody(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VarifyCodeRequestBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VarifyCodeRequestBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VarifyCodeRequestBodyDefaultTypeInternal() {}
  union {
    VarifyCodeRequestBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VarifyCodeRequestBodyDefaultTypeInternal _VarifyCodeRequestBody_default_instance_;
}  // namespace FKVerifyGrpc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_FKVerifyGrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_FKVerifyGrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_FKVerifyGrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeRequestBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeRequestBody, _impl_.request_type_),
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeRequestBody, _impl_.email_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _impl_.status_code_),
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _impl_.request_type_),
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::FKVerifyGrpc::VarifyCodeResponseBody, _impl_.varify_code_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::FKVerifyGrpc::VarifyCodeRequestBody)},
        {10, -1, -1, sizeof(::FKVerifyGrpc::VarifyCodeResponseBody)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::FKVerifyGrpc::_VarifyCodeRequestBody_default_instance_._instance,
    &::FKVerifyGrpc::_VarifyCodeResponseBody_default_instance_._instance,
};
const char descriptor_table_protodef_FKVerifyGrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022FKVerifyGrpc.proto\022\014FKVerifyGrpc\"<\n\025Va"
    "rifyCodeRequestBody\022\024\n\014request_type\030\001 \001("
    "\005\022\r\n\005email\030\002 \001(\t\"x\n\026VarifyCodeResponseBo"
    "dy\022\023\n\013status_code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t"
    "\022\024\n\014request_type\030\003 \001(\005\022\r\n\005email\030\004 \001(\t\022\023\n"
    "\013varify_code\030\005 \001(\t2q\n\021VarifyCodeService\022"
    "\\\n\rGetVarifyCode\022#.FKVerifyGrpc.VarifyCo"
    "deRequestBody\032$.FKVerifyGrpc.VarifyCodeR"
    "esponseBody\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_FKVerifyGrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_FKVerifyGrpc_2eproto = {
    false,
    false,
    341,
    descriptor_table_protodef_FKVerifyGrpc_2eproto,
    "FKVerifyGrpc.proto",
    &descriptor_table_FKVerifyGrpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_FKVerifyGrpc_2eproto::offsets,
    file_level_enum_descriptors_FKVerifyGrpc_2eproto,
    file_level_service_descriptors_FKVerifyGrpc_2eproto,
};
namespace FKVerifyGrpc {
// ===================================================================

class VarifyCodeRequestBody::_Internal {
 public:
};

VarifyCodeRequestBody::VarifyCodeRequestBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKVerifyGrpc.VarifyCodeRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE VarifyCodeRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKVerifyGrpc::VarifyCodeRequestBody& from_msg)
      : email_(arena, from.email_),
        _cached_size_{0} {}

VarifyCodeRequestBody::VarifyCodeRequestBody(
    ::google::protobuf::Arena* arena,
    const VarifyCodeRequestBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VarifyCodeRequestBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.request_type_ = from._impl_.request_type_;

  // @@protoc_insertion_point(copy_constructor:FKVerifyGrpc.VarifyCodeRequestBody)
}
inline PROTOBUF_NDEBUG_INLINE VarifyCodeRequestBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : email_(arena),
        _cached_size_{0} {}

inline void VarifyCodeRequestBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.request_type_ = {};
}
VarifyCodeRequestBody::~VarifyCodeRequestBody() {
  // @@protoc_insertion_point(destructor:FKVerifyGrpc.VarifyCodeRequestBody)
  SharedDtor(*this);
}
inline void VarifyCodeRequestBody::SharedDtor(MessageLite& self) {
  VarifyCodeRequestBody& this_ = static_cast<VarifyCodeRequestBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.email_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VarifyCodeRequestBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VarifyCodeRequestBody(arena);
}
constexpr auto VarifyCodeRequestBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VarifyCodeRequestBody),
                                            alignof(VarifyCodeRequestBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VarifyCodeRequestBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VarifyCodeRequestBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VarifyCodeRequestBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VarifyCodeRequestBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VarifyCodeRequestBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VarifyCodeRequestBody>(), &VarifyCodeRequestBody::ByteSizeLong,
            &VarifyCodeRequestBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VarifyCodeRequestBody, _impl_._cached_size_),
        false,
    },
    &VarifyCodeRequestBody::kDescriptorMethods,
    &descriptor_table_FKVerifyGrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VarifyCodeRequestBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 48, 2> VarifyCodeRequestBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKVerifyGrpc::VarifyCodeRequestBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string email = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeRequestBody, _impl_.email_)}},
    // int32 request_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VarifyCodeRequestBody, _impl_.request_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeRequestBody, _impl_.request_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 request_type = 1;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeRequestBody, _impl_.request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string email = 2;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeRequestBody, _impl_.email_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\5\0\0\0\0\0"
    "FKVerifyGrpc.VarifyCodeRequestBody"
    "email"
  }},
};

PROTOBUF_NOINLINE void VarifyCodeRequestBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKVerifyGrpc.VarifyCodeRequestBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.email_.ClearToEmpty();
  _impl_.request_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VarifyCodeRequestBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VarifyCodeRequestBody& this_ = static_cast<const VarifyCodeRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VarifyCodeRequestBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VarifyCodeRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKVerifyGrpc.VarifyCodeRequestBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 request_type = 1;
          if (this_._internal_request_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_request_type(), target);
          }

          // string email = 2;
          if (!this_._internal_email().empty()) {
            const std::string& _s = this_._internal_email();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKVerifyGrpc.VarifyCodeRequestBody.email");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKVerifyGrpc.VarifyCodeRequestBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VarifyCodeRequestBody::ByteSizeLong(const MessageLite& base) {
          const VarifyCodeRequestBody& this_ = static_cast<const VarifyCodeRequestBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VarifyCodeRequestBody::ByteSizeLong() const {
          const VarifyCodeRequestBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKVerifyGrpc.VarifyCodeRequestBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string email = 2;
            if (!this_._internal_email().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_email());
            }
            // int32 request_type = 1;
            if (this_._internal_request_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_request_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VarifyCodeRequestBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VarifyCodeRequestBody*>(&to_msg);
  auto& from = static_cast<const VarifyCodeRequestBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKVerifyGrpc.VarifyCodeRequestBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (from._internal_request_type() != 0) {
    _this->_impl_.request_type_ = from._impl_.request_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VarifyCodeRequestBody::CopyFrom(const VarifyCodeRequestBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKVerifyGrpc.VarifyCodeRequestBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VarifyCodeRequestBody::InternalSwap(VarifyCodeRequestBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
        swap(_impl_.request_type_, other->_impl_.request_type_);
}

::google::protobuf::Metadata VarifyCodeRequestBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class VarifyCodeResponseBody::_Internal {
 public:
};

VarifyCodeResponseBody::VarifyCodeResponseBody(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FKVerifyGrpc.VarifyCodeResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE VarifyCodeResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FKVerifyGrpc::VarifyCodeResponseBody& from_msg)
      : message_(arena, from.message_),
        email_(arena, from.email_),
        varify_code_(arena, from.varify_code_),
        _cached_size_{0} {}

VarifyCodeResponseBody::VarifyCodeResponseBody(
    ::google::protobuf::Arena* arena,
    const VarifyCodeResponseBody& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VarifyCodeResponseBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_code_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_code_),
           offsetof(Impl_, request_type_) -
               offsetof(Impl_, status_code_) +
               sizeof(Impl_::request_type_));

  // @@protoc_insertion_point(copy_constructor:FKVerifyGrpc.VarifyCodeResponseBody)
}
inline PROTOBUF_NDEBUG_INLINE VarifyCodeResponseBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        email_(arena),
        varify_code_(arena),
        _cached_size_{0} {}

inline void VarifyCodeResponseBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_code_),
           0,
           offsetof(Impl_, request_type_) -
               offsetof(Impl_, status_code_) +
               sizeof(Impl_::request_type_));
}
VarifyCodeResponseBody::~VarifyCodeResponseBody() {
  // @@protoc_insertion_point(destructor:FKVerifyGrpc.VarifyCodeResponseBody)
  SharedDtor(*this);
}
inline void VarifyCodeResponseBody::SharedDtor(MessageLite& self) {
  VarifyCodeResponseBody& this_ = static_cast<VarifyCodeResponseBody&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.email_.Destroy();
  this_._impl_.varify_code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VarifyCodeResponseBody::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VarifyCodeResponseBody(arena);
}
constexpr auto VarifyCodeResponseBody::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VarifyCodeResponseBody),
                                            alignof(VarifyCodeResponseBody));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VarifyCodeResponseBody::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VarifyCodeResponseBody_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VarifyCodeResponseBody::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VarifyCodeResponseBody>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VarifyCodeResponseBody::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VarifyCodeResponseBody>(), &VarifyCodeResponseBody::ByteSizeLong,
            &VarifyCodeResponseBody::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_._cached_size_),
        false,
    },
    &VarifyCodeResponseBody::kDescriptorMethods,
    &descriptor_table_FKVerifyGrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VarifyCodeResponseBody::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 67, 2> VarifyCodeResponseBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FKVerifyGrpc::VarifyCodeResponseBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 status_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VarifyCodeResponseBody, _impl_.status_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.status_code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.message_)}},
    // int32 request_type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VarifyCodeResponseBody, _impl_.request_type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.request_type_)}},
    // string email = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.email_)}},
    // string varify_code = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.varify_code_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 status_code = 1;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.status_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 request_type = 3;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.request_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string email = 4;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.email_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string varify_code = 5;
    {PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.varify_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\0\7\0\5\13\0\0"
    "FKVerifyGrpc.VarifyCodeResponseBody"
    "message"
    "email"
    "varify_code"
  }},
};

PROTOBUF_NOINLINE void VarifyCodeResponseBody::Clear() {
// @@protoc_insertion_point(message_clear_start:FKVerifyGrpc.VarifyCodeResponseBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.email_.ClearToEmpty();
  _impl_.varify_code_.ClearToEmpty();
  ::memset(&_impl_.status_code_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.request_type_) -
      reinterpret_cast<char*>(&_impl_.status_code_)) + sizeof(_impl_.request_type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VarifyCodeResponseBody::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VarifyCodeResponseBody& this_ = static_cast<const VarifyCodeResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VarifyCodeResponseBody::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VarifyCodeResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FKVerifyGrpc.VarifyCodeResponseBody)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 status_code = 1;
          if (this_._internal_status_code() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_status_code(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKVerifyGrpc.VarifyCodeResponseBody.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 request_type = 3;
          if (this_._internal_request_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_request_type(), target);
          }

          // string email = 4;
          if (!this_._internal_email().empty()) {
            const std::string& _s = this_._internal_email();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKVerifyGrpc.VarifyCodeResponseBody.email");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string varify_code = 5;
          if (!this_._internal_varify_code().empty()) {
            const std::string& _s = this_._internal_varify_code();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FKVerifyGrpc.VarifyCodeResponseBody.varify_code");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FKVerifyGrpc.VarifyCodeResponseBody)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VarifyCodeResponseBody::ByteSizeLong(const MessageLite& base) {
          const VarifyCodeResponseBody& this_ = static_cast<const VarifyCodeResponseBody&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VarifyCodeResponseBody::ByteSizeLong() const {
          const VarifyCodeResponseBody& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FKVerifyGrpc.VarifyCodeResponseBody)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // string email = 4;
            if (!this_._internal_email().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_email());
            }
            // string varify_code = 5;
            if (!this_._internal_varify_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_varify_code());
            }
            // int32 status_code = 1;
            if (this_._internal_status_code() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_status_code());
            }
            // int32 request_type = 3;
            if (this_._internal_request_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_request_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VarifyCodeResponseBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VarifyCodeResponseBody*>(&to_msg);
  auto& from = static_cast<const VarifyCodeResponseBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FKVerifyGrpc.VarifyCodeResponseBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (!from._internal_varify_code().empty()) {
    _this->_internal_set_varify_code(from._internal_varify_code());
  }
  if (from._internal_status_code() != 0) {
    _this->_impl_.status_code_ = from._impl_.status_code_;
  }
  if (from._internal_request_type() != 0) {
    _this->_impl_.request_type_ = from._impl_.request_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VarifyCodeResponseBody::CopyFrom(const VarifyCodeResponseBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FKVerifyGrpc.VarifyCodeResponseBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VarifyCodeResponseBody::InternalSwap(VarifyCodeResponseBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.varify_code_, &other->_impl_.varify_code_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.request_type_)
      + sizeof(VarifyCodeResponseBody::_impl_.request_type_)
      - PROTOBUF_FIELD_OFFSET(VarifyCodeResponseBody, _impl_.status_code_)>(
          reinterpret_cast<char*>(&_impl_.status_code_),
          reinterpret_cast<char*>(&other->_impl_.status_code_));
}

::google::protobuf::Metadata VarifyCodeResponseBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace FKVerifyGrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_FKVerifyGrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
